// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Matrix4x4 {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Matrix4x4 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

m(index: number):number|null {
    return this.bb!.readFloat32(this.bb_pos + 0 + index * 4);
}

static sizeOf():number {
  return 64;
}

static createMatrix4x4(builder:flatbuffers.Builder, m: number[]):flatbuffers.Offset {
  builder.prep(4, 64);

  for (let i = 15; i >= 0; --i) {
    builder.writeFloat32((m?.[i] ?? 0));

  }

  return builder.offset();
}

}
