// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ScriptVariableValueType {
  None = 0,
  Bool = 1,
  Int = 2,
  UInt = 3,
  Number = 4,
  String = 5,
  Vec3 = 6,
  Color = 7,
  Array = 8
}
