// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ScriptVariableValueType } from '../../../blue-bottle-ipc/league-broadcast/common/script-variable-value-type.js';
import { Vector3 } from '../../../blue-bottle-ipc/league-broadcast/common/Vector3.js';
import { Vector4 } from '../../../blue-bottle-ipc/league-broadcast/common/Vector4.js';


export class ScriptVariableValue {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScriptVariableValue {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScriptVariableValue(bb:flatbuffers.ByteBuffer, obj?:ScriptVariableValue):ScriptVariableValue {
  return (obj || new ScriptVariableValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScriptVariableValue(bb:flatbuffers.ByteBuffer, obj?:ScriptVariableValue):ScriptVariableValue {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScriptVariableValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():ScriptVariableValueType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ScriptVariableValueType.None;
}

boolValue():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

intValue():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

uintValue():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

numberValue():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

stringValue():string|null
stringValue(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
stringValue(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

vec3Value(obj?:Vector3):Vector3|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new Vector3()).__init(this.bb_pos + offset, this.bb!) : null;
}

colorValue(obj?:Vector4):Vector4|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new Vector4()).__init(this.bb_pos + offset, this.bb!) : null;
}

arrayElementType():ScriptVariableValueType {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ScriptVariableValueType.None;
}

arrayValues(index: number, obj?:ScriptVariableValue):ScriptVariableValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new ScriptVariableValue()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

arrayValuesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startScriptVariableValue(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addType(builder:flatbuffers.Builder, type:ScriptVariableValueType) {
  builder.addFieldInt8(0, type, ScriptVariableValueType.None);
}

static addBoolValue(builder:flatbuffers.Builder, boolValue:boolean) {
  builder.addFieldInt8(1, +boolValue, +false);
}

static addIntValue(builder:flatbuffers.Builder, intValue:bigint) {
  builder.addFieldInt64(2, intValue, BigInt('0'));
}

static addUintValue(builder:flatbuffers.Builder, uintValue:bigint) {
  builder.addFieldInt64(3, uintValue, BigInt('0'));
}

static addNumberValue(builder:flatbuffers.Builder, numberValue:number) {
  builder.addFieldFloat64(4, numberValue, 0.0);
}

static addStringValue(builder:flatbuffers.Builder, stringValueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, stringValueOffset, 0);
}

static addVec3Value(builder:flatbuffers.Builder, vec3ValueOffset:flatbuffers.Offset) {
  builder.addFieldStruct(6, vec3ValueOffset, 0);
}

static addColorValue(builder:flatbuffers.Builder, colorValueOffset:flatbuffers.Offset) {
  builder.addFieldStruct(7, colorValueOffset, 0);
}

static addArrayElementType(builder:flatbuffers.Builder, arrayElementType:ScriptVariableValueType) {
  builder.addFieldInt8(8, arrayElementType, ScriptVariableValueType.None);
}

static addArrayValues(builder:flatbuffers.Builder, arrayValuesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, arrayValuesOffset, 0);
}

static createArrayValuesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startArrayValuesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endScriptVariableValue(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
