// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum StrokeTipStyle {
  circle = 0,
  rectangle = 1,
  triangleArrow = 2,
  roundBackwardsArrow = 3,
  sharpBackwardsArrow = 4
}
