// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum StrokeLayer {
  underEverything = 0,
  aboveTerrain = 1,
  belowHUD = 2,
  aboveHealthbars = 3,
  twoDee = 4
}
