// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AnimationTransitionCondition } from '../../../blue-bottle-ipc/league-broadcast/entity/animation-transition-condition.js';


export class AnimationTransitionDefinition {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AnimationTransitionDefinition {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAnimationTransitionDefinition(bb:flatbuffers.ByteBuffer, obj?:AnimationTransitionDefinition):AnimationTransitionDefinition {
  return (obj || new AnimationTransitionDefinition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAnimationTransitionDefinition(bb:flatbuffers.ByteBuffer, obj?:AnimationTransitionDefinition):AnimationTransitionDefinition {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AnimationTransitionDefinition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

fromState():string|null
fromState(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
fromState(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

toState():string|null
toState(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
toState(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

condition():AnimationTransitionCondition {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AnimationTransitionCondition.Trigger;
}

trigger():string|null
trigger(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
trigger(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

afterTime():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

blendDuration():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

priority():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startAnimationTransitionDefinition(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addFromState(builder:flatbuffers.Builder, fromStateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, fromStateOffset, 0);
}

static addToState(builder:flatbuffers.Builder, toStateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, toStateOffset, 0);
}

static addCondition(builder:flatbuffers.Builder, condition:AnimationTransitionCondition) {
  builder.addFieldInt8(2, condition, AnimationTransitionCondition.Trigger);
}

static addTrigger(builder:flatbuffers.Builder, triggerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, triggerOffset, 0);
}

static addAfterTime(builder:flatbuffers.Builder, afterTime:number) {
  builder.addFieldFloat32(4, afterTime, 0.0);
}

static addBlendDuration(builder:flatbuffers.Builder, blendDuration:number) {
  builder.addFieldFloat32(5, blendDuration, 0.0);
}

static addPriority(builder:flatbuffers.Builder, priority:number) {
  builder.addFieldInt32(6, priority, 0);
}

static endAnimationTransitionDefinition(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // from_state
  builder.requiredField(offset, 6) // to_state
  return offset;
}

static createAnimationTransitionDefinition(builder:flatbuffers.Builder, fromStateOffset:flatbuffers.Offset, toStateOffset:flatbuffers.Offset, condition:AnimationTransitionCondition, triggerOffset:flatbuffers.Offset, afterTime:number, blendDuration:number, priority:number):flatbuffers.Offset {
  AnimationTransitionDefinition.startAnimationTransitionDefinition(builder);
  AnimationTransitionDefinition.addFromState(builder, fromStateOffset);
  AnimationTransitionDefinition.addToState(builder, toStateOffset);
  AnimationTransitionDefinition.addCondition(builder, condition);
  AnimationTransitionDefinition.addTrigger(builder, triggerOffset);
  AnimationTransitionDefinition.addAfterTime(builder, afterTime);
  AnimationTransitionDefinition.addBlendDuration(builder, blendDuration);
  AnimationTransitionDefinition.addPriority(builder, priority);
  return AnimationTransitionDefinition.endAnimationTransitionDefinition(builder);
}
}
