// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Skinned / static mesh instance. Drawn by MeshSystem in Shadow + Environment
 * phases. override_texture is optional and replaces the model's per-submesh
 * material textures uniformly when present.
 */
export enum AnimationTransitionCondition {
  Trigger = 0,
  AnimationComplete = 1,
  ElapsedTime = 2
}
