// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class AnimationStateDefinition {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AnimationStateDefinition {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAnimationStateDefinition(bb:flatbuffers.ByteBuffer, obj?:AnimationStateDefinition):AnimationStateDefinition {
  return (obj || new AnimationStateDefinition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAnimationStateDefinition(bb:flatbuffers.ByteBuffer, obj?:AnimationStateDefinition):AnimationStateDefinition {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AnimationStateDefinition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

clip():string|null
clip(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
clip(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

speed():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

loop():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

positionX():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

positionY():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

group():string|null
group(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
group(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startAnimationStateDefinition(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addClip(builder:flatbuffers.Builder, clipOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, clipOffset, 0);
}

static addSpeed(builder:flatbuffers.Builder, speed:number) {
  builder.addFieldFloat32(2, speed, 1.0);
}

static addLoop(builder:flatbuffers.Builder, loop:boolean) {
  builder.addFieldInt8(3, +loop, +true);
}

static addPositionX(builder:flatbuffers.Builder, positionX:number) {
  builder.addFieldFloat32(4, positionX, 0.0);
}

static addPositionY(builder:flatbuffers.Builder, positionY:number) {
  builder.addFieldFloat32(5, positionY, 0.0);
}

static addGroup(builder:flatbuffers.Builder, groupOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, groupOffset, 0);
}

static endAnimationStateDefinition(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // name
  return offset;
}

static createAnimationStateDefinition(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, clipOffset:flatbuffers.Offset, speed:number, loop:boolean, positionX:number, positionY:number, groupOffset:flatbuffers.Offset):flatbuffers.Offset {
  AnimationStateDefinition.startAnimationStateDefinition(builder);
  AnimationStateDefinition.addName(builder, nameOffset);
  AnimationStateDefinition.addClip(builder, clipOffset);
  AnimationStateDefinition.addSpeed(builder, speed);
  AnimationStateDefinition.addLoop(builder, loop);
  AnimationStateDefinition.addPositionX(builder, positionX);
  AnimationStateDefinition.addPositionY(builder, positionY);
  AnimationStateDefinition.addGroup(builder, groupOffset);
  return AnimationStateDefinition.endAnimationStateDefinition(builder);
}
}
