// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ColorRGBA } from '../../../blue-bottle-ipc/league-broadcast/common/color-rgba.js';


/**
 * Vector-font world text. Drawn by TextSystem in the WorldText phase.
 */
export class ComponentTextRenderer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ComponentTextRenderer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsComponentTextRenderer(bb:flatbuffers.ByteBuffer, obj?:ComponentTextRenderer):ComponentTextRenderer {
  return (obj || new ComponentTextRenderer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsComponentTextRenderer(bb:flatbuffers.ByteBuffer, obj?:ComponentTextRenderer):ComponentTextRenderer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ComponentTextRenderer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

fontName():string|null
fontName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
fontName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

color(obj?:ColorRGBA):ColorRGBA|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new ColorRGBA()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startComponentTextRenderer(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, textOffset, 0);
}

static addFontName(builder:flatbuffers.Builder, fontNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, fontNameOffset, 0);
}

static addColor(builder:flatbuffers.Builder, colorOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, colorOffset, 0);
}

static endComponentTextRenderer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 8) // color
  return offset;
}

}
