// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AssetIdentifier, unionToAssetIdentifier, unionListToAssetIdentifier } from '../../../blue-bottle-ipc/league-broadcast/commands/asset-identifier.js';


/**
 * Skinned / static mesh instance. Drawn by MeshSystem in Shadow + Environment
 * phases. override_texture is optional and replaces the model's per-submesh
 * material textures uniformly when present.
 */
export class ComponentMeshRenderer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ComponentMeshRenderer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsComponentMeshRenderer(bb:flatbuffers.ByteBuffer, obj?:ComponentMeshRenderer):ComponentMeshRenderer {
  return (obj || new ComponentMeshRenderer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsComponentMeshRenderer(bb:flatbuffers.ByteBuffer, obj?:ComponentMeshRenderer):ComponentMeshRenderer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ComponentMeshRenderer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

modelType():AssetIdentifier {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AssetIdentifier.NONE;
}

model<T extends flatbuffers.Table>(obj:any|string):any|string|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union_with_string(obj, this.bb_pos + offset) : null;
}

overrideTextureType():AssetIdentifier {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AssetIdentifier.NONE;
}

overrideTexture<T extends flatbuffers.Table>(obj:any|string):any|string|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__union_with_string(obj, this.bb_pos + offset) : null;
}

static startComponentMeshRenderer(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addModelType(builder:flatbuffers.Builder, modelType:AssetIdentifier) {
  builder.addFieldInt8(0, modelType, AssetIdentifier.NONE);
}

static addModel(builder:flatbuffers.Builder, modelOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, modelOffset, 0);
}

static addOverrideTextureType(builder:flatbuffers.Builder, overrideTextureType:AssetIdentifier) {
  builder.addFieldInt8(2, overrideTextureType, AssetIdentifier.NONE);
}

static addOverrideTexture(builder:flatbuffers.Builder, overrideTextureOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, overrideTextureOffset, 0);
}

static endComponentMeshRenderer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createComponentMeshRenderer(builder:flatbuffers.Builder, modelType:AssetIdentifier, modelOffset:flatbuffers.Offset, overrideTextureType:AssetIdentifier, overrideTextureOffset:flatbuffers.Offset):flatbuffers.Offset {
  ComponentMeshRenderer.startComponentMeshRenderer(builder);
  ComponentMeshRenderer.addModelType(builder, modelType);
  ComponentMeshRenderer.addModel(builder, modelOffset);
  ComponentMeshRenderer.addOverrideTextureType(builder, overrideTextureType);
  ComponentMeshRenderer.addOverrideTexture(builder, overrideTextureOffset);
  return ComponentMeshRenderer.endComponentMeshRenderer(builder);
}
}
