// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { UnitAnchorObjective } from '../../../blue-bottle-ipc/league-broadcast/entity/unit-anchor-objective.js';
import { UnitAnchorTargetType } from '../../../blue-bottle-ipc/league-broadcast/entity/unit-anchor-target-type.js';
import { UnitAnchorTeam } from '../../../blue-bottle-ipc/league-broadcast/entity/unit-anchor-team.js';


/**
 * Resolves a live League unit by network ID, stable team position, or map objective at
 * draw time. When relative_transform is enabled, the entity Transform is an offset
 * from the unit; otherwise the entity is placed exactly at the unit position.
 */
export class ComponentUnitAnchor {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ComponentUnitAnchor {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsComponentUnitAnchor(bb:flatbuffers.ByteBuffer, obj?:ComponentUnitAnchor):ComponentUnitAnchor {
  return (obj || new ComponentUnitAnchor()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsComponentUnitAnchor(bb:flatbuffers.ByteBuffer, obj?:ComponentUnitAnchor):ComponentUnitAnchor {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ComponentUnitAnchor()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

networkId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

relativeTransform():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

targetType():UnitAnchorTargetType {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : UnitAnchorTargetType.NetworkId;
}

team():UnitAnchorTeam {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : UnitAnchorTeam.Blue;
}

teamPosition():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 1;
}

objective():UnitAnchorObjective {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : UnitAnchorObjective.Grubs;
}

static startComponentUnitAnchor(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addNetworkId(builder:flatbuffers.Builder, networkId:number) {
  builder.addFieldInt32(0, networkId, 0);
}

static addRelativeTransform(builder:flatbuffers.Builder, relativeTransform:boolean) {
  builder.addFieldInt8(1, +relativeTransform, +true);
}

static addTargetType(builder:flatbuffers.Builder, targetType:UnitAnchorTargetType) {
  builder.addFieldInt8(2, targetType, UnitAnchorTargetType.NetworkId);
}

static addTeam(builder:flatbuffers.Builder, team:UnitAnchorTeam) {
  builder.addFieldInt8(3, team, UnitAnchorTeam.Blue);
}

static addTeamPosition(builder:flatbuffers.Builder, teamPosition:number) {
  builder.addFieldInt8(4, teamPosition, 1);
}

static addObjective(builder:flatbuffers.Builder, objective:UnitAnchorObjective) {
  builder.addFieldInt8(5, objective, UnitAnchorObjective.Grubs);
}

static endComponentUnitAnchor(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createComponentUnitAnchor(builder:flatbuffers.Builder, networkId:number, relativeTransform:boolean, targetType:UnitAnchorTargetType, team:UnitAnchorTeam, teamPosition:number, objective:UnitAnchorObjective):flatbuffers.Offset {
  ComponentUnitAnchor.startComponentUnitAnchor(builder);
  ComponentUnitAnchor.addNetworkId(builder, networkId);
  ComponentUnitAnchor.addRelativeTransform(builder, relativeTransform);
  ComponentUnitAnchor.addTargetType(builder, targetType);
  ComponentUnitAnchor.addTeam(builder, team);
  ComponentUnitAnchor.addTeamPosition(builder, teamPosition);
  ComponentUnitAnchor.addObjective(builder, objective);
  return ComponentUnitAnchor.endComponentUnitAnchor(builder);
}
}
