// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Stable kind tag, used by RemoveComponent / GetComponents and for in-memory
 * component-bag indexing. MUST stay in lockstep with the Component union below.
 */
export enum ComponentKind {
  Transform = 0,
  Visibility = 1,
  EditState = 2,
  Script = 3,
  MeshRenderer = 4,
  DecalProjector = 5,
  TextRenderer = 6,
  StreamSource = 7,
  SpriteRenderer = 8
}
