// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ComponentDecalProjector } from '../../../blue-bottle-ipc/league-broadcast/entity/component-decal-projector.js';
import { ComponentEditState } from '../../../blue-bottle-ipc/league-broadcast/entity/component-edit-state.js';
import { ComponentMeshRenderer } from '../../../blue-bottle-ipc/league-broadcast/entity/component-mesh-renderer.js';
import { ComponentScript } from '../../../blue-bottle-ipc/league-broadcast/entity/component-script.js';
import { ComponentStreamSource } from '../../../blue-bottle-ipc/league-broadcast/entity/component-stream-source.js';
import { ComponentTextRenderer } from '../../../blue-bottle-ipc/league-broadcast/entity/component-text-renderer.js';
import { ComponentTransform } from '../../../blue-bottle-ipc/league-broadcast/entity/component-transform.js';
import { ComponentVisibility } from '../../../blue-bottle-ipc/league-broadcast/entity/component-visibility.js';


export enum Component {
  NONE = 0,
  Transform = 1,
  Visibility = 2,
  EditState = 3,
  Script = 4,
  MeshRenderer = 5,
  DecalProjector = 6,
  TextRenderer = 7,
  StreamSource = 8
}

export function unionToComponent(
  type: Component,
  accessor: (obj:ComponentDecalProjector|ComponentEditState|ComponentMeshRenderer|ComponentScript|ComponentStreamSource|ComponentTextRenderer|ComponentTransform|ComponentVisibility) => ComponentDecalProjector|ComponentEditState|ComponentMeshRenderer|ComponentScript|ComponentStreamSource|ComponentTextRenderer|ComponentTransform|ComponentVisibility|null
): ComponentDecalProjector|ComponentEditState|ComponentMeshRenderer|ComponentScript|ComponentStreamSource|ComponentTextRenderer|ComponentTransform|ComponentVisibility|null {
  switch(Component[type]) {
    case 'NONE': return null; 
    case 'Transform': return accessor(new ComponentTransform())! as ComponentTransform;
    case 'Visibility': return accessor(new ComponentVisibility())! as ComponentVisibility;
    case 'EditState': return accessor(new ComponentEditState())! as ComponentEditState;
    case 'Script': return accessor(new ComponentScript())! as ComponentScript;
    case 'MeshRenderer': return accessor(new ComponentMeshRenderer())! as ComponentMeshRenderer;
    case 'DecalProjector': return accessor(new ComponentDecalProjector())! as ComponentDecalProjector;
    case 'TextRenderer': return accessor(new ComponentTextRenderer())! as ComponentTextRenderer;
    case 'StreamSource': return accessor(new ComponentStreamSource())! as ComponentStreamSource;
    default: return null;
  }
}

export function unionListToComponent(
  type: Component, 
  accessor: (index: number, obj:ComponentDecalProjector|ComponentEditState|ComponentMeshRenderer|ComponentScript|ComponentStreamSource|ComponentTextRenderer|ComponentTransform|ComponentVisibility) => ComponentDecalProjector|ComponentEditState|ComponentMeshRenderer|ComponentScript|ComponentStreamSource|ComponentTextRenderer|ComponentTransform|ComponentVisibility|null, 
  index: number
): ComponentDecalProjector|ComponentEditState|ComponentMeshRenderer|ComponentScript|ComponentStreamSource|ComponentTextRenderer|ComponentTransform|ComponentVisibility|null {
  switch(Component[type]) {
    case 'NONE': return null; 
    case 'Transform': return accessor(index, new ComponentTransform())! as ComponentTransform;
    case 'Visibility': return accessor(index, new ComponentVisibility())! as ComponentVisibility;
    case 'EditState': return accessor(index, new ComponentEditState())! as ComponentEditState;
    case 'Script': return accessor(index, new ComponentScript())! as ComponentScript;
    case 'MeshRenderer': return accessor(index, new ComponentMeshRenderer())! as ComponentMeshRenderer;
    case 'DecalProjector': return accessor(index, new ComponentDecalProjector())! as ComponentDecalProjector;
    case 'TextRenderer': return accessor(index, new ComponentTextRenderer())! as ComponentTextRenderer;
    case 'StreamSource': return accessor(index, new ComponentStreamSource())! as ComponentStreamSource;
    default: return null;
  }
}
