// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AssetIdentifier, unionToAssetIdentifier, unionListToAssetIdentifier } from '../../../blue-bottle-ipc/league-broadcast/commands/asset-identifier.js';


/**
 * Projected texture quad rendered against a depth-buffer copy. Drawn by
 * DecalSystem in the Decals phase.
 */
export class ComponentDecalProjector {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ComponentDecalProjector {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsComponentDecalProjector(bb:flatbuffers.ByteBuffer, obj?:ComponentDecalProjector):ComponentDecalProjector {
  return (obj || new ComponentDecalProjector()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsComponentDecalProjector(bb:flatbuffers.ByteBuffer, obj?:ComponentDecalProjector):ComponentDecalProjector {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ComponentDecalProjector()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

textureType():AssetIdentifier {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AssetIdentifier.NONE;
}

texture<T extends flatbuffers.Table>(obj:any|string):any|string|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union_with_string(obj, this.bb_pos + offset) : null;
}

angleThreshold():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startComponentDecalProjector(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addTextureType(builder:flatbuffers.Builder, textureType:AssetIdentifier) {
  builder.addFieldInt8(0, textureType, AssetIdentifier.NONE);
}

static addTexture(builder:flatbuffers.Builder, textureOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, textureOffset, 0);
}

static addAngleThreshold(builder:flatbuffers.Builder, angleThreshold:number) {
  builder.addFieldFloat32(2, angleThreshold, 0.0);
}

static endComponentDecalProjector(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createComponentDecalProjector(builder:flatbuffers.Builder, textureType:AssetIdentifier, textureOffset:flatbuffers.Offset, angleThreshold:number):flatbuffers.Offset {
  ComponentDecalProjector.startComponentDecalProjector(builder);
  ComponentDecalProjector.addTextureType(builder, textureType);
  ComponentDecalProjector.addTexture(builder, textureOffset);
  ComponentDecalProjector.addAngleThreshold(builder, angleThreshold);
  return ComponentDecalProjector.endComponentDecalProjector(builder);
}
}
