// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Quaternion } from '../../../blue-bottle-ipc/league-broadcast/common/Quaternion.js';
import { Vector3 } from '../../../blue-bottle-ipc/league-broadcast/common/Vector3.js';


/**
 * Position / rotation / scale plus parent linkage. parent_id = 0 means
 * "child of the scene root". Re-parenting is a SetComponent(Transform) with
 * the new parent_id (and unchanged pos/rot/scale, since component sets are
 * always full per design §5.3).
 */
export class ComponentTransform {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ComponentTransform {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsComponentTransform(bb:flatbuffers.ByteBuffer, obj?:ComponentTransform):ComponentTransform {
  return (obj || new ComponentTransform()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsComponentTransform(bb:flatbuffers.ByteBuffer, obj?:ComponentTransform):ComponentTransform {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ComponentTransform()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

position(obj?:Vector3):Vector3|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Vector3()).__init(this.bb_pos + offset, this.bb!) : null;
}

rotation(obj?:Quaternion):Quaternion|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Quaternion()).__init(this.bb_pos + offset, this.bb!) : null;
}

scale(obj?:Vector3):Vector3|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Vector3()).__init(this.bb_pos + offset, this.bb!) : null;
}

parentId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startComponentTransform(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, positionOffset, 0);
}

static addRotation(builder:flatbuffers.Builder, rotationOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, rotationOffset, 0);
}

static addScale(builder:flatbuffers.Builder, scaleOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, scaleOffset, 0);
}

static addParentId(builder:flatbuffers.Builder, parentId:bigint) {
  builder.addFieldInt64(3, parentId, BigInt('0'));
}

static endComponentTransform(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // position
  builder.requiredField(offset, 6) // rotation
  builder.requiredField(offset, 8) // scale
  return offset;
}

}
