// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AssetIdentifier, unionToAssetIdentifier, unionListToAssetIdentifier } from '../../../blue-bottle-ipc/league-broadcast/commands/asset-identifier.js';
import { ColorRGBA } from '../../../blue-bottle-ipc/league-broadcast/common/color-rgba.js';


/**
 * Camera-facing billboarded textured quad. Drawn by SpriteSystem in the
 * WorldText phase. The texture is a managed / broadcast asset (e.g. a team
 * logo). width/height are world units; when billboard is true the quad always
 * faces the broadcast camera. Used by the dynamic-cinematics feature for logos.
 */
export class ComponentSpriteRenderer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ComponentSpriteRenderer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsComponentSpriteRenderer(bb:flatbuffers.ByteBuffer, obj?:ComponentSpriteRenderer):ComponentSpriteRenderer {
  return (obj || new ComponentSpriteRenderer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsComponentSpriteRenderer(bb:flatbuffers.ByteBuffer, obj?:ComponentSpriteRenderer):ComponentSpriteRenderer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ComponentSpriteRenderer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

textureType():AssetIdentifier {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AssetIdentifier.NONE;
}

texture<T extends flatbuffers.Table>(obj:any|string):any|string|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union_with_string(obj, this.bb_pos + offset) : null;
}

tintColor(obj?:ColorRGBA):ColorRGBA|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new ColorRGBA()).__init(this.bb_pos + offset, this.bb!) : null;
}

width():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

height():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

billboard():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

static startComponentSpriteRenderer(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addTextureType(builder:flatbuffers.Builder, textureType:AssetIdentifier) {
  builder.addFieldInt8(0, textureType, AssetIdentifier.NONE);
}

static addTexture(builder:flatbuffers.Builder, textureOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, textureOffset, 0);
}

static addTintColor(builder:flatbuffers.Builder, tintColorOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, tintColorOffset, 0);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldFloat32(3, width, 1.0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldFloat32(4, height, 1.0);
}

static addBillboard(builder:flatbuffers.Builder, billboard:boolean) {
  builder.addFieldInt8(5, +billboard, +true);
}

static endComponentSpriteRenderer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
