// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ScriptEntry } from '../../../blue-bottle-ipc/league-broadcast/entity/script-entry.js';


export class ComponentScript {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ComponentScript {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsComponentScript(bb:flatbuffers.ByteBuffer, obj?:ComponentScript):ComponentScript {
  return (obj || new ComponentScript()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsComponentScript(bb:flatbuffers.ByteBuffer, obj?:ComponentScript):ComponentScript {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ComponentScript()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

scripts(index: number, obj?:ScriptEntry):ScriptEntry|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ScriptEntry()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

scriptsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startComponentScript(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addScripts(builder:flatbuffers.Builder, scriptsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, scriptsOffset, 0);
}

static createScriptsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startScriptsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endComponentScript(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createComponentScript(builder:flatbuffers.Builder, scriptsOffset:flatbuffers.Offset):flatbuffers.Offset {
  ComponentScript.startComponentScript(builder);
  ComponentScript.addScripts(builder, scriptsOffset);
  return ComponentScript.endComponentScript(builder);
}
}
