// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Per-entity visibility and opacity. Per-entity visible = false hides the
 * entity without removing it (gap from the old BBObject model where only
 * per-scene visibility existed).
 */
export class ComponentVisibility {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ComponentVisibility {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsComponentVisibility(bb:flatbuffers.ByteBuffer, obj?:ComponentVisibility):ComponentVisibility {
  return (obj || new ComponentVisibility()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsComponentVisibility(bb:flatbuffers.ByteBuffer, obj?:ComponentVisibility):ComponentVisibility {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ComponentVisibility()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

visible():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

opacity():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

static startComponentVisibility(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addVisible(builder:flatbuffers.Builder, visible:boolean) {
  builder.addFieldInt8(0, +visible, +true);
}

static addOpacity(builder:flatbuffers.Builder, opacity:number) {
  builder.addFieldFloat32(1, opacity, 1.0);
}

static endComponentVisibility(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createComponentVisibility(builder:flatbuffers.Builder, visible:boolean, opacity:number):flatbuffers.Offset {
  ComponentVisibility.startComponentVisibility(builder);
  ComponentVisibility.addVisible(builder, visible);
  ComponentVisibility.addOpacity(builder, opacity);
  return ComponentVisibility.endComponentVisibility(builder);
}
}
