// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Editor-only state. edit_mode toggles the edit-PS variant in DecalSystem /
 * TextSystem; linked_to_cursor is set while the user is dragging an entity
 * into place before the click that drops it (see SceneObjectPlaced event).
 */
export class ComponentEditState {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ComponentEditState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsComponentEditState(bb:flatbuffers.ByteBuffer, obj?:ComponentEditState):ComponentEditState {
  return (obj || new ComponentEditState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsComponentEditState(bb:flatbuffers.ByteBuffer, obj?:ComponentEditState):ComponentEditState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ComponentEditState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

editMode():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

linkedToCursor():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startComponentEditState(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addEditMode(builder:flatbuffers.Builder, editMode:boolean) {
  builder.addFieldInt8(0, +editMode, +false);
}

static addLinkedToCursor(builder:flatbuffers.Builder, linkedToCursor:boolean) {
  builder.addFieldInt8(1, +linkedToCursor, +false);
}

static endComponentEditState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createComponentEditState(builder:flatbuffers.Builder, editMode:boolean, linkedToCursor:boolean):flatbuffers.Offset {
  ComponentEditState.startComponentEditState(builder);
  ComponentEditState.addEditMode(builder, editMode);
  ComponentEditState.addLinkedToCursor(builder, linkedToCursor);
  return ComponentEditState.endComponentEditState(builder);
}
}
