// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * WHIP-streamed video source bound to a sibling renderer's texture asset.
 * Driven by StreamSourceSystem (added once feature/video-integration lands
 * on develop). The texture itself lives in TextureManager as a stream-asset
 * variant; this component owns the WHIP session lifecycle only.
 *
 * Format mirrors the C++ StreamFormat enum (H265, H264, ...). Kept as ubyte
 * here so the schema doesn't need an explicit enum until video lands.
 */
export class ComponentStreamSource {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ComponentStreamSource {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsComponentStreamSource(bb:flatbuffers.ByteBuffer, obj?:ComponentStreamSource):ComponentStreamSource {
  return (obj || new ComponentStreamSource()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsComponentStreamSource(bb:flatbuffers.ByteBuffer, obj?:ComponentStreamSource):ComponentStreamSource {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ComponentStreamSource()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

streamName():string|null
streamName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
streamName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

format():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

autoStart():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startComponentStreamSource(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addStreamName(builder:flatbuffers.Builder, streamNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, streamNameOffset, 0);
}

static addFormat(builder:flatbuffers.Builder, format:number) {
  builder.addFieldInt8(1, format, 0);
}

static addAutoStart(builder:flatbuffers.Builder, autoStart:boolean) {
  builder.addFieldInt8(2, +autoStart, +false);
}

static endComponentStreamSource(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createComponentStreamSource(builder:flatbuffers.Builder, streamNameOffset:flatbuffers.Offset, format:number, autoStart:boolean):flatbuffers.Offset {
  ComponentStreamSource.startComponentStreamSource(builder);
  ComponentStreamSource.addStreamName(builder, streamNameOffset);
  ComponentStreamSource.addFormat(builder, format);
  ComponentStreamSource.addAutoStart(builder, autoStart);
  return ComponentStreamSource.endComponentStreamSource(builder);
}
}
