// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Lua script attached to the entity. Detaching = RemoveComponent(Script).
 * An entity can carry multiple scripts; each ScriptEntry gets its own
 * sandboxed Lua environment with `self` pointing to the owning entity.
 *
 * script_id + variable_overrides are persistence-only fields used by C# to
 * resolve library references. lblib ignores them and only reads name/content/enabled.
 */
export class ScriptVariableOverride {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScriptVariableOverride {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScriptVariableOverride(bb:flatbuffers.ByteBuffer, obj?:ScriptVariableOverride):ScriptVariableOverride {
  return (obj || new ScriptVariableOverride()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScriptVariableOverride(bb:flatbuffers.ByteBuffer, obj?:ScriptVariableOverride):ScriptVariableOverride {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScriptVariableOverride()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

value():string|null
value(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
value(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startScriptVariableOverride(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static endScriptVariableOverride(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // name
  return offset;
}

static createScriptVariableOverride(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  ScriptVariableOverride.startScriptVariableOverride(builder);
  ScriptVariableOverride.addName(builder, nameOffset);
  ScriptVariableOverride.addValue(builder, valueOffset);
  return ScriptVariableOverride.endScriptVariableOverride(builder);
}
}
