// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ScriptVariableValue } from '../../../blue-bottle-ipc/league-broadcast/common/script-variable-value.js';


/**
 * AngelScript class attached to the entity. Detaching = RemoveComponent(Script).
 * An entity can carry multiple scripts; each ScriptEntry gets its own
 * sandboxed object with `self` pointing to the owning entity.
 *
 * script_id is a persistence-only field used by C# to resolve library references.
 * lblib applies variable_overrides to matching fields on the script object.
 */
export class ScriptVariableOverride {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScriptVariableOverride {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScriptVariableOverride(bb:flatbuffers.ByteBuffer, obj?:ScriptVariableOverride):ScriptVariableOverride {
  return (obj || new ScriptVariableOverride()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScriptVariableOverride(bb:flatbuffers.ByteBuffer, obj?:ScriptVariableOverride):ScriptVariableOverride {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScriptVariableOverride()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

value():string|null
value(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
value(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

typedValue(obj?:ScriptVariableValue):ScriptVariableValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new ScriptVariableValue()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startScriptVariableOverride(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static addTypedValue(builder:flatbuffers.Builder, typedValueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, typedValueOffset, 0);
}

static endScriptVariableOverride(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // name
  return offset;
}

}
