// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ScriptVariableOverride } from '../../../blue-bottle-ipc/league-broadcast/entity/script-variable-override.js';


export class ScriptEntry {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScriptEntry {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScriptEntry(bb:flatbuffers.ByteBuffer, obj?:ScriptEntry):ScriptEntry {
  return (obj || new ScriptEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScriptEntry(bb:flatbuffers.ByteBuffer, obj?:ScriptEntry):ScriptEntry {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScriptEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

content():string|null
content(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
content(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

enabled():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

scriptId():string|null
scriptId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
scriptId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

variableOverrides(index: number, obj?:ScriptVariableOverride):ScriptVariableOverride|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new ScriptVariableOverride()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

variableOverridesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startScriptEntry(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addContent(builder:flatbuffers.Builder, contentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, contentOffset, 0);
}

static addEnabled(builder:flatbuffers.Builder, enabled:boolean) {
  builder.addFieldInt8(2, +enabled, +true);
}

static addScriptId(builder:flatbuffers.Builder, scriptIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, scriptIdOffset, 0);
}

static addVariableOverrides(builder:flatbuffers.Builder, variableOverridesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, variableOverridesOffset, 0);
}

static createVariableOverridesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startVariableOverridesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endScriptEntry(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createScriptEntry(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, contentOffset:flatbuffers.Offset, enabled:boolean, scriptIdOffset:flatbuffers.Offset, variableOverridesOffset:flatbuffers.Offset):flatbuffers.Offset {
  ScriptEntry.startScriptEntry(builder);
  ScriptEntry.addName(builder, nameOffset);
  ScriptEntry.addContent(builder, contentOffset);
  ScriptEntry.addEnabled(builder, enabled);
  ScriptEntry.addScriptId(builder, scriptIdOffset);
  ScriptEntry.addVariableOverrides(builder, variableOverridesOffset);
  return ScriptEntry.endScriptEntry(builder);
}
}
