// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Live map objective a UnitAnchor follows. Values mirror the sequencer's
 * CameraLookAtObjective; resolveUnitAnchorObject serves both surfaces.
 */
export enum UnitAnchorObjective {
  Grubs = 0,
  RiftHerald = 1,
  Dragon = 2,
  Baron = 3
}
