// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum UnitAnchorTargetType {
  NetworkId = 0,
  TeamPosition = 1,
  Objective = 2
}
