// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TargetKind } from '../../../blue-bottle-ipc/league-broadcast/sequencer/target-kind.js';


/**
 * A Track names a binding by id, never by entity id, so re-pointing a broken binding
 * rewrites one row and touches no keyframe.
 */
export class Binding {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Binding {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBinding(bb:flatbuffers.ByteBuffer, obj?:Binding):Binding {
  return (obj || new Binding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBinding(bb:flatbuffers.ByteBuffer, obj?:Binding):Binding {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Binding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

target():TargetKind {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TargetKind.Entity;
}

entityName():string|null
entityName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
entityName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

entityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

propId():string|null
propId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
propId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

label():string|null
label(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
label(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

sceneName():string|null
sceneName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sceneName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startBinding(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addTarget(builder:flatbuffers.Builder, target:TargetKind) {
  builder.addFieldInt8(1, target, TargetKind.Entity);
}

static addEntityName(builder:flatbuffers.Builder, entityNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, entityNameOffset, 0);
}

static addEntityId(builder:flatbuffers.Builder, entityId:bigint) {
  builder.addFieldInt64(3, entityId, BigInt('0'));
}

static addPropId(builder:flatbuffers.Builder, propIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, propIdOffset, 0);
}

static addLabel(builder:flatbuffers.Builder, labelOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, labelOffset, 0);
}

static addSceneName(builder:flatbuffers.Builder, sceneNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, sceneNameOffset, 0);
}

static endBinding(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createBinding(builder:flatbuffers.Builder, id:number, target:TargetKind, entityNameOffset:flatbuffers.Offset, entityId:bigint, propIdOffset:flatbuffers.Offset, labelOffset:flatbuffers.Offset, sceneNameOffset:flatbuffers.Offset):flatbuffers.Offset {
  Binding.startBinding(builder);
  Binding.addId(builder, id);
  Binding.addTarget(builder, target);
  Binding.addEntityName(builder, entityNameOffset);
  Binding.addEntityId(builder, entityId);
  Binding.addPropId(builder, propIdOffset);
  Binding.addLabel(builder, labelOffset);
  Binding.addSceneName(builder, sceneNameOffset);
  return Binding.endBinding(builder);
}
}
