// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CameraLookAtObjective } from '../../../blue-bottle-ipc/league-broadcast/sequencer/camera-look-at-objective.js';
import { CameraLookAtSource } from '../../../blue-bottle-ipc/league-broadcast/sequencer/camera-look-at-source.js';
import { CameraLookAtTeam } from '../../../blue-bottle-ipc/league-broadcast/sequencer/camera-look-at-team.js';


/**
 * One camera keyframe's focus target: what the point aims at while its CameraAimBlend key
 * is above zero. Sparse — only aiming points carry a row — and each row's time matches a
 * CameraPosition key. Within a segment the source point's row wins; when it has none, the
 * destination point's row applies, so a fade-in sweeps toward the target being faded to.
 */
export class CameraFocusPoint {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CameraFocusPoint {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCameraFocusPoint(bb:flatbuffers.ByteBuffer, obj?:CameraFocusPoint):CameraFocusPoint {
  return (obj || new CameraFocusPoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCameraFocusPoint(bb:flatbuffers.ByteBuffer, obj?:CameraFocusPoint):CameraFocusPoint {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CameraFocusPoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

time():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

source():CameraLookAtSource {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : CameraLookAtSource.Channel;
}

binding():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

networkId():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

team():CameraLookAtTeam {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : CameraLookAtTeam.Blue;
}

teamPosition():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 1;
}

objective():CameraLookAtObjective {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : CameraLookAtObjective.Grubs;
}

offsetX():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

offsetY():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

offsetZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startCameraFocusPoint(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addTime(builder:flatbuffers.Builder, time:number) {
  builder.addFieldFloat32(0, time, 0.0);
}

static addSource(builder:flatbuffers.Builder, source:CameraLookAtSource) {
  builder.addFieldInt8(1, source, CameraLookAtSource.Channel);
}

static addBinding(builder:flatbuffers.Builder, binding:number) {
  builder.addFieldInt32(2, binding, 0);
}

static addNetworkId(builder:flatbuffers.Builder, networkId:number) {
  builder.addFieldInt32(3, networkId, 0);
}

static addTeam(builder:flatbuffers.Builder, team:CameraLookAtTeam) {
  builder.addFieldInt8(4, team, CameraLookAtTeam.Blue);
}

static addTeamPosition(builder:flatbuffers.Builder, teamPosition:number) {
  builder.addFieldInt8(5, teamPosition, 1);
}

static addObjective(builder:flatbuffers.Builder, objective:CameraLookAtObjective) {
  builder.addFieldInt8(6, objective, CameraLookAtObjective.Grubs);
}

static addOffsetX(builder:flatbuffers.Builder, offsetX:number) {
  builder.addFieldFloat32(7, offsetX, 0.0);
}

static addOffsetY(builder:flatbuffers.Builder, offsetY:number) {
  builder.addFieldFloat32(8, offsetY, 0.0);
}

static addOffsetZ(builder:flatbuffers.Builder, offsetZ:number) {
  builder.addFieldFloat32(9, offsetZ, 0.0);
}

static endCameraFocusPoint(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCameraFocusPoint(builder:flatbuffers.Builder, time:number, source:CameraLookAtSource, binding:number, networkId:number, team:CameraLookAtTeam, teamPosition:number, objective:CameraLookAtObjective, offsetX:number, offsetY:number, offsetZ:number):flatbuffers.Offset {
  CameraFocusPoint.startCameraFocusPoint(builder);
  CameraFocusPoint.addTime(builder, time);
  CameraFocusPoint.addSource(builder, source);
  CameraFocusPoint.addBinding(builder, binding);
  CameraFocusPoint.addNetworkId(builder, networkId);
  CameraFocusPoint.addTeam(builder, team);
  CameraFocusPoint.addTeamPosition(builder, teamPosition);
  CameraFocusPoint.addObjective(builder, objective);
  CameraFocusPoint.addOffsetX(builder, offsetX);
  CameraFocusPoint.addOffsetY(builder, offsetY);
  CameraFocusPoint.addOffsetZ(builder, offsetZ);
  return CameraFocusPoint.endCameraFocusPoint(builder);
}
}
