// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CameraLookAtObjective } from '../../../blue-bottle-ipc/league-broadcast/sequencer/camera-look-at-objective.js';
import { CameraLookAtSource } from '../../../blue-bottle-ipc/league-broadcast/sequencer/camera-look-at-source.js';
import { CameraLookAtTeam } from '../../../blue-bottle-ipc/league-broadcast/sequencer/camera-look-at-team.js';


export class CameraLookAtSettings {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CameraLookAtSettings {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCameraLookAtSettings(bb:flatbuffers.ByteBuffer, obj?:CameraLookAtSettings):CameraLookAtSettings {
  return (obj || new CameraLookAtSettings()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCameraLookAtSettings(bb:flatbuffers.ByteBuffer, obj?:CameraLookAtSettings):CameraLookAtSettings {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CameraLookAtSettings()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

source():CameraLookAtSource {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : CameraLookAtSource.None;
}

binding():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

networkId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

team():CameraLookAtTeam {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : CameraLookAtTeam.Blue;
}

teamPosition():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 1;
}

objective():CameraLookAtObjective {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : CameraLookAtObjective.Grubs;
}

offsetX():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

offsetY():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

offsetZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startCameraLookAtSettings(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addSource(builder:flatbuffers.Builder, source:CameraLookAtSource) {
  builder.addFieldInt8(0, source, CameraLookAtSource.None);
}

static addBinding(builder:flatbuffers.Builder, binding:number) {
  builder.addFieldInt32(1, binding, 0);
}

static addNetworkId(builder:flatbuffers.Builder, networkId:number) {
  builder.addFieldInt32(2, networkId, 0);
}

static addTeam(builder:flatbuffers.Builder, team:CameraLookAtTeam) {
  builder.addFieldInt8(3, team, CameraLookAtTeam.Blue);
}

static addTeamPosition(builder:flatbuffers.Builder, teamPosition:number) {
  builder.addFieldInt8(4, teamPosition, 1);
}

static addObjective(builder:flatbuffers.Builder, objective:CameraLookAtObjective) {
  builder.addFieldInt8(5, objective, CameraLookAtObjective.Grubs);
}

static addOffsetX(builder:flatbuffers.Builder, offsetX:number) {
  builder.addFieldFloat32(6, offsetX, 0.0);
}

static addOffsetY(builder:flatbuffers.Builder, offsetY:number) {
  builder.addFieldFloat32(7, offsetY, 0.0);
}

static addOffsetZ(builder:flatbuffers.Builder, offsetZ:number) {
  builder.addFieldFloat32(8, offsetZ, 0.0);
}

static endCameraLookAtSettings(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCameraLookAtSettings(builder:flatbuffers.Builder, source:CameraLookAtSource, binding:number, networkId:number, team:CameraLookAtTeam, teamPosition:number, objective:CameraLookAtObjective, offsetX:number, offsetY:number, offsetZ:number):flatbuffers.Offset {
  CameraLookAtSettings.startCameraLookAtSettings(builder);
  CameraLookAtSettings.addSource(builder, source);
  CameraLookAtSettings.addBinding(builder, binding);
  CameraLookAtSettings.addNetworkId(builder, networkId);
  CameraLookAtSettings.addTeam(builder, team);
  CameraLookAtSettings.addTeamPosition(builder, teamPosition);
  CameraLookAtSettings.addObjective(builder, objective);
  CameraLookAtSettings.addOffsetX(builder, offsetX);
  CameraLookAtSettings.addOffsetY(builder, offsetY);
  CameraLookAtSettings.addOffsetZ(builder, offsetZ);
  return CameraLookAtSettings.endCameraLookAtSettings(builder);
}
}
