// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Whether the sequence is actually driving the game camera, and if not, what holds it.
 * A camera track that silently does nothing because the FPS follower owns the camera is
 * otherwise indistinguishable from a broken one.
 */
export enum CameraHold {
  Idle = 0,
  Driving = 1,
  BlockedByFollower = 2,
  BlockedBySource = 3,
  NoGameCamera = 4
}
