// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Camera translation and aim are independent, matching a physical dolly plus operator.
 * Channel samples CameraLookAtTarget. Entity reads a scene entity's resolved world transform.
 * Unit sources resolve a live League object directly.
 */
export enum CameraLookAtSource {
  None = 0,
  Channel = 1,
  Entity = 2,
  UnitNetworkId = 3,
  UnitTeamPosition = 4,
  UnitObjective = 5
}
