// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Live map objective the camera follows. Values mirror the scene-entity
 * UnitAnchorObjective selector; both surfaces resolve through one anchor resolver.
 */
export enum CameraLookAtObjective {
  Grubs = 0,
  RiftHerald = 1,
  Dragon = 2,
  Baron = 3
}
