// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Which fields of SeqKeyframe a channel reads, and how two keys blend.
 */
export enum ChannelValue {
  Scalar = 0,
  Vec3 = 1,
  Euler3 = 2,
  Quat = 3,
  Color = 4,
  Bool = 5
}
