// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ChannelValue } from '../../../blue-bottle-ipc/league-broadcast/sequencer/channel-value.js';
import { SeqKeyframe } from '../../../blue-bottle-ipc/league-broadcast/sequencer/seq-keyframe.js';
import { SeqProperty } from '../../../blue-bottle-ipc/league-broadcast/sequencer/seq-property.js';


export class Channel {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Channel {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChannel(bb:flatbuffers.ByteBuffer, obj?:Channel):Channel {
  return (obj || new Channel()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChannel(bb:flatbuffers.ByteBuffer, obj?:Channel):Channel {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Channel()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

property():SeqProperty {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : SeqProperty.TransformPosition;
}

value():ChannelValue {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ChannelValue.Scalar;
}

keys(index: number, obj?:SeqKeyframe):SeqKeyframe|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new SeqKeyframe()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

keysLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startChannel(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addProperty(builder:flatbuffers.Builder, property:SeqProperty) {
  builder.addFieldInt16(0, property, SeqProperty.TransformPosition);
}

static addValue(builder:flatbuffers.Builder, value:ChannelValue) {
  builder.addFieldInt8(1, value, ChannelValue.Scalar);
}

static addKeys(builder:flatbuffers.Builder, keysOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, keysOffset, 0);
}

static createKeysVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startKeysVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endChannel(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChannel(builder:flatbuffers.Builder, property:SeqProperty, value:ChannelValue, keysOffset:flatbuffers.Offset):flatbuffers.Offset {
  Channel.startChannel(builder);
  Channel.addProperty(builder, property);
  Channel.addValue(builder, value);
  Channel.addKeys(builder, keysOffset);
  return Channel.endChannel(builder);
}
}
