// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Which protected region of the clip the playhead is in. lblib derives it from
 * in_end/out_start so the authoring and operator surfaces read one state machine
 * instead of each re-deriving marker positions and disagreeing on air.
 */
export enum ClipPhase {
  In = 0,
  Hold = 1,
  Out = 2
}
