// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Marker } from '../../../blue-bottle-ipc/league-broadcast/sequencer/Marker.js';
import { Track } from '../../../blue-bottle-ipc/league-broadcast/sequencer/Track.js';


/**
 * [0, in_end) and [out_start, duration) are protected regions: a duration change
 * stretches only the middle. in_end == out_start == 0 means uniform stretch.
 */
export class Clip {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Clip {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsClip(bb:flatbuffers.ByteBuffer, obj?:Clip):Clip {
  return (obj || new Clip()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsClip(bb:flatbuffers.ByteBuffer, obj?:Clip):Clip {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Clip()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

duration():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

inEnd():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

outStart():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

loopHold():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

logicLayer():string|null
logicLayer(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
logicLayer(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Deprecated compatibility metadata for old generic documents. Native cinematic camera assets
 * bind Camera tracks directly; lblib never reads this handoff field.
 */
cameraSequenceName():string|null
cameraSequenceName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cameraSequenceName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

autoStart():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

tracks(index: number, obj?:Track):Track|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new Track()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

tracksLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

markers(index: number, obj?:Marker):Marker|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new Marker()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

markersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startClip(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addDuration(builder:flatbuffers.Builder, duration:number) {
  builder.addFieldFloat32(1, duration, 0.0);
}

static addInEnd(builder:flatbuffers.Builder, inEnd:number) {
  builder.addFieldFloat32(2, inEnd, 0.0);
}

static addOutStart(builder:flatbuffers.Builder, outStart:number) {
  builder.addFieldFloat32(3, outStart, 0.0);
}

static addLoopHold(builder:flatbuffers.Builder, loopHold:boolean) {
  builder.addFieldInt8(4, +loopHold, +false);
}

static addLogicLayer(builder:flatbuffers.Builder, logicLayerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, logicLayerOffset, 0);
}

static addCameraSequenceName(builder:flatbuffers.Builder, cameraSequenceNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, cameraSequenceNameOffset, 0);
}

static addAutoStart(builder:flatbuffers.Builder, autoStart:boolean) {
  builder.addFieldInt8(7, +autoStart, +false);
}

static addTracks(builder:flatbuffers.Builder, tracksOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, tracksOffset, 0);
}

static createTracksVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTracksVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addMarkers(builder:flatbuffers.Builder, markersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, markersOffset, 0);
}

static createMarkersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMarkersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endClip(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // name
  return offset;
}

static createClip(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, duration:number, inEnd:number, outStart:number, loopHold:boolean, logicLayerOffset:flatbuffers.Offset, cameraSequenceNameOffset:flatbuffers.Offset, autoStart:boolean, tracksOffset:flatbuffers.Offset, markersOffset:flatbuffers.Offset):flatbuffers.Offset {
  Clip.startClip(builder);
  Clip.addName(builder, nameOffset);
  Clip.addDuration(builder, duration);
  Clip.addInEnd(builder, inEnd);
  Clip.addOutStart(builder, outStart);
  Clip.addLoopHold(builder, loopHold);
  Clip.addLogicLayer(builder, logicLayerOffset);
  Clip.addCameraSequenceName(builder, cameraSequenceNameOffset);
  Clip.addAutoStart(builder, autoStart);
  Clip.addTracks(builder, tracksOffset);
  Clip.addMarkers(builder, markersOffset);
  return Clip.endClip(builder);
}
}
