// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ExposedChoice {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ExposedChoice {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsExposedChoice(bb:flatbuffers.ByteBuffer, obj?:ExposedChoice):ExposedChoice {
  return (obj || new ExposedChoice()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsExposedChoice(bb:flatbuffers.ByteBuffer, obj?:ExposedChoice):ExposedChoice {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ExposedChoice()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

label():string|null
label(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
label(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

value():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startExposedChoice(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addLabel(builder:flatbuffers.Builder, labelOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, labelOffset, 0);
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldFloat32(1, value, 0.0);
}

static endExposedChoice(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // label
  return offset;
}

static createExposedChoice(builder:flatbuffers.Builder, labelOffset:flatbuffers.Offset, value:number):flatbuffers.Offset {
  ExposedChoice.startExposedChoice(builder);
  ExposedChoice.addLabel(builder, labelOffset);
  ExposedChoice.addValue(builder, value);
  return ExposedChoice.endExposedChoice(builder);
}
}
