// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Blender NLA semantics. Nothing = contribute only inside [start, end);
 * Hold = clamp to the nearest key outside the range; HoldForward = clamp forward only.
 */
export enum Extrapolation {
  Nothing = 0,
  Hold = 1,
  HoldForward = 2
}
