// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MarkerKind } from '../../../blue-bottle-ipc/league-broadcast/sequencer/marker-kind.js';


export class Marker {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Marker {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMarker(bb:flatbuffers.ByteBuffer, obj?:Marker):Marker {
  return (obj || new Marker()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMarker(bb:flatbuffers.ByteBuffer, obj?:Marker):Marker {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Marker()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

time():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

kind():MarkerKind {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MarkerKind.Tag;
}

retroactive():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

emitOnce():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

/**
 * Pause only: wall seconds to freeze before resuming by itself. 0 freezes until Continue.
 */
pauseDuration():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startMarker(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addTime(builder:flatbuffers.Builder, time:number) {
  builder.addFieldFloat32(0, time, 0.0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addKind(builder:flatbuffers.Builder, kind:MarkerKind) {
  builder.addFieldInt8(2, kind, MarkerKind.Tag);
}

static addRetroactive(builder:flatbuffers.Builder, retroactive:boolean) {
  builder.addFieldInt8(3, +retroactive, +false);
}

static addEmitOnce(builder:flatbuffers.Builder, emitOnce:boolean) {
  builder.addFieldInt8(4, +emitOnce, +true);
}

static addPauseDuration(builder:flatbuffers.Builder, pauseDuration:number) {
  builder.addFieldFloat32(5, pauseDuration, 0.0);
}

static endMarker(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // name
  return offset;
}

static createMarker(builder:flatbuffers.Builder, time:number, nameOffset:flatbuffers.Offset, kind:MarkerKind, retroactive:boolean, emitOnce:boolean, pauseDuration:number):flatbuffers.Offset {
  Marker.startMarker(builder);
  Marker.addTime(builder, time);
  Marker.addName(builder, nameOffset);
  Marker.addKind(builder, kind);
  Marker.addRetroactive(builder, retroactive);
  Marker.addEmitOnce(builder, emitOnce);
  Marker.addPauseDuration(builder, pauseDuration);
  return Marker.endMarker(builder);
}
}
