// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Tag marks a position. Stop halts this clip and every clip sharing its logic_layer.
 * LocalStop halts only this clip. Pause freezes without releasing bound properties.
 * Signal fires an event to the host and does nothing locally.
 */
export enum MarkerKind {
  Tag = 0,
  Stop = 1,
  LocalStop = 2,
  Pause = 3,
  Signal = 4
}
