// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum SectionBlend {
  Replace = 0,
  Add = 1,
  Multiply = 2,
  Combine = 3
}
