// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BlendEasing } from '../../../blue-bottle-ipc/league-broadcast/cinematics/blend-easing.js';
import { Channel } from '../../../blue-bottle-ipc/league-broadcast/sequencer/Channel.js';
import { Extrapolation } from '../../../blue-bottle-ipc/league-broadcast/sequencer/Extrapolation.js';
import { SectionBlend } from '../../../blue-bottle-ipc/league-broadcast/sequencer/section-blend.js';
import { SeqKeyframe } from '../../../blue-bottle-ipc/league-broadcast/sequencer/seq-keyframe.js';


/**
 * Inclusive start, exclusive end. Written down because nothing else in this repo
 * states a range convention.
 */
export class Section {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Section {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSection(bb:flatbuffers.ByteBuffer, obj?:Section):Section {
  return (obj || new Section()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSection(bb:flatbuffers.ByteBuffer, obj?:Section):Section {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Section()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

start():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

end():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

blend():SectionBlend {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : SectionBlend.Replace;
}

extrapolation():Extrapolation {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Extrapolation.Hold;
}

influence(index: number, obj?:SeqKeyframe):SeqKeyframe|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new SeqKeyframe()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

influenceLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

easeIn():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

easeOut():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

easeInCurve():BlendEasing {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BlendEasing.SmoothStep;
}

easeOutCurve():BlendEasing {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BlendEasing.SmoothStep;
}

muted():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

channels(index: number, obj?:Channel):Channel|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? (obj || new Channel()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

channelsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSection(builder:flatbuffers.Builder) {
  builder.startObject(11);
}

static addStart(builder:flatbuffers.Builder, start:number) {
  builder.addFieldFloat32(0, start, 0.0);
}

static addEnd(builder:flatbuffers.Builder, end:number) {
  builder.addFieldFloat32(1, end, 0.0);
}

static addBlend(builder:flatbuffers.Builder, blend:SectionBlend) {
  builder.addFieldInt8(2, blend, SectionBlend.Replace);
}

static addExtrapolation(builder:flatbuffers.Builder, extrapolation:Extrapolation) {
  builder.addFieldInt8(3, extrapolation, Extrapolation.Hold);
}

static addInfluence(builder:flatbuffers.Builder, influenceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, influenceOffset, 0);
}

static createInfluenceVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startInfluenceVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addEaseIn(builder:flatbuffers.Builder, easeIn:number) {
  builder.addFieldFloat32(5, easeIn, 0.0);
}

static addEaseOut(builder:flatbuffers.Builder, easeOut:number) {
  builder.addFieldFloat32(6, easeOut, 0.0);
}

static addEaseInCurve(builder:flatbuffers.Builder, easeInCurve:BlendEasing) {
  builder.addFieldInt8(7, easeInCurve, BlendEasing.SmoothStep);
}

static addEaseOutCurve(builder:flatbuffers.Builder, easeOutCurve:BlendEasing) {
  builder.addFieldInt8(8, easeOutCurve, BlendEasing.SmoothStep);
}

static addMuted(builder:flatbuffers.Builder, muted:boolean) {
  builder.addFieldInt8(9, +muted, +false);
}

static addChannels(builder:flatbuffers.Builder, channelsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, channelsOffset, 0);
}

static createChannelsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startChannelsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSection(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSection(builder:flatbuffers.Builder, start:number, end:number, blend:SectionBlend, extrapolation:Extrapolation, influenceOffset:flatbuffers.Offset, easeIn:number, easeOut:number, easeInCurve:BlendEasing, easeOutCurve:BlendEasing, muted:boolean, channelsOffset:flatbuffers.Offset):flatbuffers.Offset {
  Section.startSection(builder);
  Section.addStart(builder, start);
  Section.addEnd(builder, end);
  Section.addBlend(builder, blend);
  Section.addExtrapolation(builder, extrapolation);
  Section.addInfluence(builder, influenceOffset);
  Section.addEaseIn(builder, easeIn);
  Section.addEaseOut(builder, easeOut);
  Section.addEaseInCurve(builder, easeInCurve);
  Section.addEaseOutCurve(builder, easeOutCurve);
  Section.addMuted(builder, muted);
  Section.addChannels(builder, channelsOffset);
  return Section.endSection(builder);
}
}
