// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * A flat (component, field) pair. The only place the animatable set is enumerated on
 * the wire; the native PropertyTable X-macro must stay in lockstep with it and a
 * static_assert pins the count. Appending is safe, reordering is not.
 */
export enum SeqProperty {
  TransformPosition = 0,
  TransformRotation = 1,
  TransformScale = 2,
  VisibilityVisible = 3,
  VisibilityOpacity = 4,
  MeshAnimationTime = 5,
  MeshAnimationSpeed = 6,
  MeshAnimationLoop = 7,
  MeshAnimationPlaying = 8,
  DecalAngleThreshold = 9,
  TextColor = 10,
  SpriteTint = 11,
  SpriteWidth = 12,
  SpriteHeight = 13,
  CameraPosition = 14,
  CameraRotation = 15,
  CameraZoom = 16,
  CameraFov = 17,
  CameraLookAtTarget = 18,

  /**
   * Per camera point: 0 evaluates that point's CameraRotation key, 1 aims it at that
   * point's camera_focus_points row. Intermediate values slerp, so a point that
   * switches modes crossfades instead of cutting. Absent channel = every point aims at
   * its own row; pre-v6 documents read the channel against the track's camera_look_at
   * instead, which every v7 document lacks.
   */
  CameraAimBlend = 19
}
