// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BlendEasing } from '../../../blue-bottle-ipc/league-broadcast/cinematics/blend-easing.js';
import { CameraTangentMode } from '../../../blue-bottle-ipc/league-broadcast/sequencer/camera-tangent-mode.js';


/**
 * Field-for-field identical to CinematicKeyframe so the C# reference evaluator and the
 * C++ one sample the same bytes with the same code.
 */
export class SeqKeyframe {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SeqKeyframe {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSeqKeyframe(bb:flatbuffers.ByteBuffer, obj?:SeqKeyframe):SeqKeyframe {
  return (obj || new SeqKeyframe()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSeqKeyframe(bb:flatbuffers.ByteBuffer, obj?:SeqKeyframe):SeqKeyframe {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SeqKeyframe()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

time():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

z():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

floatValue():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

boolValue():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

easing():BlendEasing {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BlendEasing.Linear;
}

tangentMode():CameraTangentMode {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : CameraTangentMode.Auto;
}

tangentX():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

tangentY():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

tangentZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

tangentsSplit():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

incomingTangentX():number {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

incomingTangentY():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

incomingTangentZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startSeqKeyframe(builder:flatbuffers.Builder) {
  builder.startObject(15);
}

static addTime(builder:flatbuffers.Builder, time:number) {
  builder.addFieldFloat32(0, time, 0.0);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldFloat32(1, x, 0.0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldFloat32(2, y, 0.0);
}

static addZ(builder:flatbuffers.Builder, z:number) {
  builder.addFieldFloat32(3, z, 0.0);
}

static addFloatValue(builder:flatbuffers.Builder, floatValue:number) {
  builder.addFieldFloat32(4, floatValue, 0.0);
}

static addBoolValue(builder:flatbuffers.Builder, boolValue:boolean) {
  builder.addFieldInt8(5, +boolValue, +false);
}

static addEasing(builder:flatbuffers.Builder, easing:BlendEasing) {
  builder.addFieldInt8(6, easing, BlendEasing.Linear);
}

static addTangentMode(builder:flatbuffers.Builder, tangentMode:CameraTangentMode) {
  builder.addFieldInt8(7, tangentMode, CameraTangentMode.Auto);
}

static addTangentX(builder:flatbuffers.Builder, tangentX:number) {
  builder.addFieldFloat32(8, tangentX, 0.0);
}

static addTangentY(builder:flatbuffers.Builder, tangentY:number) {
  builder.addFieldFloat32(9, tangentY, 0.0);
}

static addTangentZ(builder:flatbuffers.Builder, tangentZ:number) {
  builder.addFieldFloat32(10, tangentZ, 0.0);
}

static addTangentsSplit(builder:flatbuffers.Builder, tangentsSplit:boolean) {
  builder.addFieldInt8(11, +tangentsSplit, +false);
}

static addIncomingTangentX(builder:flatbuffers.Builder, incomingTangentX:number) {
  builder.addFieldFloat32(12, incomingTangentX, 0.0);
}

static addIncomingTangentY(builder:flatbuffers.Builder, incomingTangentY:number) {
  builder.addFieldFloat32(13, incomingTangentY, 0.0);
}

static addIncomingTangentZ(builder:flatbuffers.Builder, incomingTangentZ:number) {
  builder.addFieldFloat32(14, incomingTangentZ, 0.0);
}

static endSeqKeyframe(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSeqKeyframe(builder:flatbuffers.Builder, time:number, x:number, y:number, z:number, floatValue:number, boolValue:boolean, easing:BlendEasing, tangentMode:CameraTangentMode, tangentX:number, tangentY:number, tangentZ:number, tangentsSplit:boolean, incomingTangentX:number, incomingTangentY:number, incomingTangentZ:number):flatbuffers.Offset {
  SeqKeyframe.startSeqKeyframe(builder);
  SeqKeyframe.addTime(builder, time);
  SeqKeyframe.addX(builder, x);
  SeqKeyframe.addY(builder, y);
  SeqKeyframe.addZ(builder, z);
  SeqKeyframe.addFloatValue(builder, floatValue);
  SeqKeyframe.addBoolValue(builder, boolValue);
  SeqKeyframe.addEasing(builder, easing);
  SeqKeyframe.addTangentMode(builder, tangentMode);
  SeqKeyframe.addTangentX(builder, tangentX);
  SeqKeyframe.addTangentY(builder, tangentY);
  SeqKeyframe.addTangentZ(builder, tangentZ);
  SeqKeyframe.addTangentsSplit(builder, tangentsSplit);
  SeqKeyframe.addIncomingTangentX(builder, incomingTangentX);
  SeqKeyframe.addIncomingTangentY(builder, incomingTangentY);
  SeqKeyframe.addIncomingTangentZ(builder, incomingTangentZ);
  return SeqKeyframe.endSeqKeyframe(builder);
}
}
