// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Binding } from '../../../blue-bottle-ipc/league-broadcast/sequencer/Binding.js';
import { Clip } from '../../../blue-bottle-ipc/league-broadcast/sequencer/Clip.js';
import { Exposed } from '../../../blue-bottle-ipc/league-broadcast/sequencer/Exposed.js';


export class Sequence {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Sequence {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSequence(bb:flatbuffers.ByteBuffer, obj?:Sequence):Sequence {
  return (obj || new Sequence()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSequence(bb:flatbuffers.ByteBuffer, obj?:Sequence):Sequence {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Sequence()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static bufferHasIdentifier(bb:flatbuffers.ByteBuffer):boolean {
  return bb.__has_identifier('BBSQ');
}

/**
 * Bump only when a field lblib READS changes meaning, because lblib refuses any
 * document newer than the version it was built against. Appending a field that
 * only the host reads must NOT bump this, or an old lblib kills playback outright
 * over a field it never needed.
 *
 * 2: Marker.pause_duration. An lblib that ignores it leaves a timed Pause frozen for
 * ever, so refusing the document outright is the safer failure.
 * 3: Camera position keyframes may provide manual tangent derivatives. An older lblib
 * would silently evaluate a different camera path, so it must refuse these documents.
 * 4: Manual camera position keyframes may split their incoming and outgoing tangent
 * derivatives. Older lblib builds would incorrectly use the outgoing derivative on both sides.
 * 5: Camera tracks may continuously derive pitch/yaw from a sampled or live look-at target.
 * Older lblib builds would silently keep evaluating only keyframed rotation.
 * 6: Camera points may each choose keyframed rotation or the track's focus target through
 * CameraAimBlend. An older lblib ignores the channel and aims every point the same way,
 * so it must refuse these documents rather than fly a path nobody authored.
 * 7: Camera focus is per keyframe: camera_focus_points replaces the track-level
 * camera_look_at, and targets may be live map objectives. An older lblib would fly
 * keyframed rotation only, so it must refuse these documents.
 */
schemaVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 2;
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

sceneName():string|null
sceneName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sceneName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

frameRate():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 60.0;
}

bindings(index: number, obj?:Binding):Binding|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new Binding()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

bindingsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

clips(index: number, obj?:Clip):Clip|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new Clip()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

clipsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

exposed(index: number, obj?:Exposed):Exposed|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new Exposed()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

exposedLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSequence(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addSchemaVersion(builder:flatbuffers.Builder, schemaVersion:number) {
  builder.addFieldInt16(0, schemaVersion, 2);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, idOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nameOffset, 0);
}

static addSceneName(builder:flatbuffers.Builder, sceneNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, sceneNameOffset, 0);
}

static addFrameRate(builder:flatbuffers.Builder, frameRate:number) {
  builder.addFieldFloat32(4, frameRate, 60.0);
}

static addBindings(builder:flatbuffers.Builder, bindingsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, bindingsOffset, 0);
}

static createBindingsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startBindingsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addClips(builder:flatbuffers.Builder, clipsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, clipsOffset, 0);
}

static createClipsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startClipsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addExposed(builder:flatbuffers.Builder, exposedOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, exposedOffset, 0);
}

static createExposedVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startExposedVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSequence(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // id
  return offset;
}

static finishSequenceBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'BBSQ');
}

static finishSizePrefixedSequenceBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'BBSQ', true);
}

static createSequence(builder:flatbuffers.Builder, schemaVersion:number, idOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, sceneNameOffset:flatbuffers.Offset, frameRate:number, bindingsOffset:flatbuffers.Offset, clipsOffset:flatbuffers.Offset, exposedOffset:flatbuffers.Offset):flatbuffers.Offset {
  Sequence.startSequence(builder);
  Sequence.addSchemaVersion(builder, schemaVersion);
  Sequence.addId(builder, idOffset);
  Sequence.addName(builder, nameOffset);
  Sequence.addSceneName(builder, sceneNameOffset);
  Sequence.addFrameRate(builder, frameRate);
  Sequence.addBindings(builder, bindingsOffset);
  Sequence.addClips(builder, clipsOffset);
  Sequence.addExposed(builder, exposedOffset);
  return Sequence.endSequence(builder);
}
}
