// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ClipPhase } from '../../../blue-bottle-ipc/league-broadcast/sequencer/clip-phase.js';


/**
 * The clock is per clip run, not per document: two clips can be on air at different
 * local times, and one clip's out may overlap another's in.
 */
export class SequenceClipState {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SequenceClipState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSequenceClipState(bb:flatbuffers.ByteBuffer, obj?:SequenceClipState):SequenceClipState {
  return (obj || new SequenceClipState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSequenceClipState(bb:flatbuffers.ByteBuffer, obj?:SequenceClipState):SequenceClipState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SequenceClipState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

time():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

epoch():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

playing():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

phase():ClipPhase {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ClipPhase.In;
}

haltedAtMarker():string|null
haltedAtMarker(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
haltedAtMarker(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSequenceClipState(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addTime(builder:flatbuffers.Builder, time:number) {
  builder.addFieldFloat32(1, time, 0.0);
}

static addEpoch(builder:flatbuffers.Builder, epoch:bigint) {
  builder.addFieldInt64(2, epoch, BigInt('0'));
}

static addPlaying(builder:flatbuffers.Builder, playing:boolean) {
  builder.addFieldInt8(3, +playing, +false);
}

static addPhase(builder:flatbuffers.Builder, phase:ClipPhase) {
  builder.addFieldInt8(4, phase, ClipPhase.In);
}

static addHaltedAtMarker(builder:flatbuffers.Builder, haltedAtMarkerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, haltedAtMarkerOffset, 0);
}

static endSequenceClipState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSequenceClipState(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, time:number, epoch:bigint, playing:boolean, phase:ClipPhase, haltedAtMarkerOffset:flatbuffers.Offset):flatbuffers.Offset {
  SequenceClipState.startSequenceClipState(builder);
  SequenceClipState.addName(builder, nameOffset);
  SequenceClipState.addTime(builder, time);
  SequenceClipState.addEpoch(builder, epoch);
  SequenceClipState.addPlaying(builder, playing);
  SequenceClipState.addPhase(builder, phase);
  SequenceClipState.addHaltedAtMarker(builder, haltedAtMarkerOffset);
  return SequenceClipState.endSequenceClipState(builder);
}
}
