// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CameraHold } from '../../../blue-bottle-ipc/league-broadcast/sequencer/camera-hold.js';
import { SeqProperty } from '../../../blue-bottle-ipc/league-broadcast/sequencer/seq-property.js';
import { SequenceClipState } from '../../../blue-bottle-ipc/league-broadcast/sequencer/sequence-clip-state.js';


export class SequenceState {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SequenceState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSequenceState(bb:flatbuffers.ByteBuffer, obj?:SequenceState):SequenceState {
  return (obj || new SequenceState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSequenceState(bb:flatbuffers.ByteBuffer, obj?:SequenceState):SequenceState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SequenceState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sequenceId():string|null
sequenceId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sequenceId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

clips(index: number, obj?:SequenceClipState):SequenceClipState|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new SequenceClipState()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

clipsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

brokenBindings(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

brokenBindingsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

brokenBindingsArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

firedMarkers(index: number):string
firedMarkers(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
firedMarkers(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

firedMarkersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

/**
 * Every property this lblib build can actually write. The host REPLACES its
 * compile-time capability list with this, so a property gaining a native setter
 * needs no host change at all.
 */
drivableProperties(index: number):SeqProperty|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

drivablePropertiesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

drivablePropertiesArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

camera():CameraHold {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : CameraHold.Idle;
}

static startSequenceState(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addSequenceId(builder:flatbuffers.Builder, sequenceIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, sequenceIdOffset, 0);
}

static addClips(builder:flatbuffers.Builder, clipsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, clipsOffset, 0);
}

static createClipsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startClipsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addBrokenBindings(builder:flatbuffers.Builder, brokenBindingsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, brokenBindingsOffset, 0);
}

static createBrokenBindingsVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createBrokenBindingsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createBrokenBindingsVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startBrokenBindingsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addFiredMarkers(builder:flatbuffers.Builder, firedMarkersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, firedMarkersOffset, 0);
}

static createFiredMarkersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFiredMarkersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addDrivableProperties(builder:flatbuffers.Builder, drivablePropertiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, drivablePropertiesOffset, 0);
}

static createDrivablePropertiesVector(builder:flatbuffers.Builder, data:SeqProperty[]):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startDrivablePropertiesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static addCamera(builder:flatbuffers.Builder, camera:CameraHold) {
  builder.addFieldInt8(5, camera, CameraHold.Idle);
}

static endSequenceState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSequenceState(builder:flatbuffers.Builder, sequenceIdOffset:flatbuffers.Offset, clipsOffset:flatbuffers.Offset, brokenBindingsOffset:flatbuffers.Offset, firedMarkersOffset:flatbuffers.Offset, drivablePropertiesOffset:flatbuffers.Offset, camera:CameraHold):flatbuffers.Offset {
  SequenceState.startSequenceState(builder);
  SequenceState.addSequenceId(builder, sequenceIdOffset);
  SequenceState.addClips(builder, clipsOffset);
  SequenceState.addBrokenBindings(builder, brokenBindingsOffset);
  SequenceState.addFiredMarkers(builder, firedMarkersOffset);
  SequenceState.addDrivableProperties(builder, drivablePropertiesOffset);
  SequenceState.addCamera(builder, camera);
  return SequenceState.endSequenceState(builder);
}
}
