// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CameraFocusPoint } from '../../../blue-bottle-ipc/league-broadcast/sequencer/camera-focus-point.js';
import { CameraLookAtSettings } from '../../../blue-bottle-ipc/league-broadcast/sequencer/camera-look-at-settings.js';
import { Section } from '../../../blue-bottle-ipc/league-broadcast/sequencer/Section.js';


export class Track {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Track {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTrack(bb:flatbuffers.ByteBuffer, obj?:Track):Track {
  return (obj || new Track()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTrack(bb:flatbuffers.ByteBuffer, obj?:Track):Track {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Track()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

binding():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

sections(index: number, obj?:Section):Section|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Section()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

sectionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

muted():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

locked():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 * Pre-v7 path-level focus target. It never shipped, so ingest ignores it and v7 writers
 * never set it; removal is a separate change.
 */
cameraLookAt(obj?:CameraLookAtSettings):CameraLookAtSettings|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new CameraLookAtSettings()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * Camera tracks only: per-keyframe focus targets. Sparse, time-matched to position keys.
 */
cameraFocusPoints(index: number, obj?:CameraFocusPoint):CameraFocusPoint|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new CameraFocusPoint()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

cameraFocusPointsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startTrack(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addBinding(builder:flatbuffers.Builder, binding:number) {
  builder.addFieldInt32(1, binding, 0);
}

static addSections(builder:flatbuffers.Builder, sectionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, sectionsOffset, 0);
}

static createSectionsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSectionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addMuted(builder:flatbuffers.Builder, muted:boolean) {
  builder.addFieldInt8(3, +muted, +false);
}

static addLocked(builder:flatbuffers.Builder, locked:boolean) {
  builder.addFieldInt8(4, +locked, +false);
}

static addCameraLookAt(builder:flatbuffers.Builder, cameraLookAtOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, cameraLookAtOffset, 0);
}

static addCameraFocusPoints(builder:flatbuffers.Builder, cameraFocusPointsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, cameraFocusPointsOffset, 0);
}

static createCameraFocusPointsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCameraFocusPointsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endTrack(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
