// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PlayerSlot } from '../../../blue-bottle-ipc/league-broadcast/cinematics/player-slot.js';
import { TeamSlot } from '../../../blue-bottle-ipc/league-broadcast/cinematics/team-slot.js';


export class AddPlayerVideoRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AddPlayerVideoRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAddPlayerVideoRequest(bb:flatbuffers.ByteBuffer, obj?:AddPlayerVideoRequest):AddPlayerVideoRequest {
  return (obj || new AddPlayerVideoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAddPlayerVideoRequest(bb:flatbuffers.ByteBuffer, obj?:AddPlayerVideoRequest):AddPlayerVideoRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AddPlayerVideoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cinematicId():string|null
cinematicId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cinematicId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

teamSlot():TeamSlot {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TeamSlot.Team1;
}

playerSlot():PlayerSlot {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : PlayerSlot.Player1;
}

static startAddPlayerVideoRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addCinematicId(builder:flatbuffers.Builder, cinematicIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cinematicIdOffset, 0);
}

static addTeamSlot(builder:flatbuffers.Builder, teamSlot:TeamSlot) {
  builder.addFieldInt8(1, teamSlot, TeamSlot.Team1);
}

static addPlayerSlot(builder:flatbuffers.Builder, playerSlot:PlayerSlot) {
  builder.addFieldInt8(2, playerSlot, PlayerSlot.Player1);
}

static endAddPlayerVideoRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAddPlayerVideoRequest(builder:flatbuffers.Builder, cinematicIdOffset:flatbuffers.Offset, teamSlot:TeamSlot, playerSlot:PlayerSlot):flatbuffers.Offset {
  AddPlayerVideoRequest.startAddPlayerVideoRequest(builder);
  AddPlayerVideoRequest.addCinematicId(builder, cinematicIdOffset);
  AddPlayerVideoRequest.addTeamSlot(builder, teamSlot);
  AddPlayerVideoRequest.addPlayerSlot(builder, playerSlot);
  return AddPlayerVideoRequest.endAddPlayerVideoRequest(builder);
}
}
