// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class AddModelRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AddModelRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAddModelRequest(bb:flatbuffers.ByteBuffer, obj?:AddModelRequest):AddModelRequest {
  return (obj || new AddModelRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAddModelRequest(bb:flatbuffers.ByteBuffer, obj?:AddModelRequest):AddModelRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AddModelRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cinematicId():string|null
cinematicId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cinematicId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

modelAsset():string|null
modelAsset(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
modelAsset(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startAddModelRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCinematicId(builder:flatbuffers.Builder, cinematicIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cinematicIdOffset, 0);
}

static addModelAsset(builder:flatbuffers.Builder, modelAssetOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, modelAssetOffset, 0);
}

static endAddModelRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAddModelRequest(builder:flatbuffers.Builder, cinematicIdOffset:flatbuffers.Offset, modelAssetOffset:flatbuffers.Offset):flatbuffers.Offset {
  AddModelRequest.startAddModelRequest(builder);
  AddModelRequest.addCinematicId(builder, cinematicIdOffset);
  AddModelRequest.addModelAsset(builder, modelAssetOffset);
  return AddModelRequest.endAddModelRequest(builder);
}
}
