// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Easing curves for keyframe interpolation. Mirrors the 33 replay-sequence BlendOptions
 * names one-to-one so a cinematic keyframe eases identically to a camera-flight keyframe.
 */
export enum BlendEasing {
  Linear = 0,
  Snap = 1,
  SmoothStep = 2,
  SmootherStep = 3,
  QuadraticEaseIn = 4,
  QuadraticEaseOut = 5,
  QuadraticEaseInOut = 6,
  CubicEaseIn = 7,
  CubicEaseOut = 8,
  CubicEaseInOut = 9,
  QuarticEaseIn = 10,
  QuarticEaseOut = 11,
  QuarticEaseInOut = 12,
  QuinticEaseIn = 13,
  QuinticEaseOut = 14,
  QuinticEaseInOut = 15,
  SineEaseIn = 16,
  SineEaseOut = 17,
  SineEaseInOut = 18,
  CircularEaseIn = 19,
  CircularEaseOut = 20,
  CircularEaseInOut = 21,
  ExponentialEaseIn = 22,
  ExponentialEaseOut = 23,
  ExponentialEaseInOut = 24,
  ElasticEaseIn = 25,
  ElasticEaseOut = 26,
  ElasticEaseInOut = 27,
  BackEaseIn = 28,
  BackEaseOut = 29,
  BackEaseInOut = 30,
  BounceEaseIn = 31,
  BounceEaseOut = 32,
  BounceEaseInOut = 33
}
