// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum BoundTextSource {
  Team1Name = 0,
  Team2Name = 1,
  ScoreLine = 2,
  Team1Score = 3,
  Team2Score = 4,
  GameClock = 5,
  Team1Kills = 6,
  Team2Kills = 7
}
