// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Live playback status pushed over the playback subscription.
 */
export class CinematicPlayback {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CinematicPlayback {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCinematicPlayback(bb:flatbuffers.ByteBuffer, obj?:CinematicPlayback):CinematicPlayback {
  return (obj || new CinematicPlayback()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCinematicPlayback(bb:flatbuffers.ByteBuffer, obj?:CinematicPlayback):CinematicPlayback {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CinematicPlayback()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cinematicId():string|null
cinematicId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cinematicId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

time():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

length():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

state():string|null
state(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
state(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

playing():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startCinematicPlayback(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addCinematicId(builder:flatbuffers.Builder, cinematicIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cinematicIdOffset, 0);
}

static addTime(builder:flatbuffers.Builder, time:number) {
  builder.addFieldFloat32(1, time, 0.0);
}

static addLength(builder:flatbuffers.Builder, length:number) {
  builder.addFieldFloat32(2, length, 0.0);
}

static addState(builder:flatbuffers.Builder, stateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, stateOffset, 0);
}

static addPlaying(builder:flatbuffers.Builder, playing:boolean) {
  builder.addFieldInt8(4, +playing, +false);
}

static endCinematicPlayback(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCinematicPlayback(builder:flatbuffers.Builder, cinematicIdOffset:flatbuffers.Offset, time:number, length:number, stateOffset:flatbuffers.Offset, playing:boolean):flatbuffers.Offset {
  CinematicPlayback.startCinematicPlayback(builder);
  CinematicPlayback.addCinematicId(builder, cinematicIdOffset);
  CinematicPlayback.addTime(builder, time);
  CinematicPlayback.addLength(builder, length);
  CinematicPlayback.addState(builder, stateOffset);
  CinematicPlayback.addPlaying(builder, playing);
  return CinematicPlayback.endCinematicPlayback(builder);
}
}
