// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CinematicProp } from '../../../blue-bottle-ipc/league-broadcast/cinematics/cinematic-prop.js';


/**
 * A dynamic cinematic: a named camera flight plus managed props animated along it.
 */
export class Cinematic {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Cinematic {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCinematic(bb:flatbuffers.ByteBuffer, obj?:Cinematic):Cinematic {
  return (obj || new Cinematic()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCinematic(bb:flatbuffers.ByteBuffer, obj?:Cinematic):Cinematic {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Cinematic()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

cameraSequenceName():string|null
cameraSequenceName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cameraSequenceName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

props(index: number, obj?:CinematicProp):CinematicProp|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new CinematicProp()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

propsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startCinematic(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addCameraSequenceName(builder:flatbuffers.Builder, cameraSequenceNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, cameraSequenceNameOffset, 0);
}

static addProps(builder:flatbuffers.Builder, propsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, propsOffset, 0);
}

static createPropsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPropsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endCinematic(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCinematic(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, cameraSequenceNameOffset:flatbuffers.Offset, propsOffset:flatbuffers.Offset):flatbuffers.Offset {
  Cinematic.startCinematic(builder);
  Cinematic.addId(builder, idOffset);
  Cinematic.addName(builder, nameOffset);
  Cinematic.addCameraSequenceName(builder, cameraSequenceNameOffset);
  Cinematic.addProps(builder, propsOffset);
  return Cinematic.endCinematic(builder);
}
}
