// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BoundTextSource } from '../../../blue-bottle-ipc/league-broadcast/cinematics/bound-text-source.js';
import { CinematicTrack } from '../../../blue-bottle-ipc/league-broadcast/cinematics/cinematic-track.js';
import { PropKind } from '../../../blue-bottle-ipc/league-broadcast/cinematics/prop-kind.js';
import { PropStyle } from '../../../blue-bottle-ipc/league-broadcast/cinematics/prop-style.js';
import { TeamSlot } from '../../../blue-bottle-ipc/league-broadcast/cinematics/team-slot.js';
import { TextFormat } from '../../../blue-bottle-ipc/league-broadcast/cinematics/text-format.js';


/**
 * One animated prop in a cinematic. Carries only enumerated bindings (no free content).
 */
export class CinematicProp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CinematicProp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCinematicProp(bb:flatbuffers.ByteBuffer, obj?:CinematicProp):CinematicProp {
  return (obj || new CinematicProp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCinematicProp(bb:flatbuffers.ByteBuffer, obj?:CinematicProp):CinematicProp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CinematicProp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

kind():PropKind {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : PropKind.BoundText;
}

source():BoundTextSource {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BoundTextSource.Team1Name;
}

format():TextFormat {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TextFormat.Default;
}

teamSlot():TeamSlot {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TeamSlot.Team1;
}

tracks(index: number, obj?:CinematicTrack):CinematicTrack|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new CinematicTrack()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

tracksLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

style(obj?:PropStyle):PropStyle|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new PropStyle()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startCinematicProp(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addKind(builder:flatbuffers.Builder, kind:PropKind) {
  builder.addFieldInt8(1, kind, PropKind.BoundText);
}

static addSource(builder:flatbuffers.Builder, source:BoundTextSource) {
  builder.addFieldInt8(2, source, BoundTextSource.Team1Name);
}

static addFormat(builder:flatbuffers.Builder, format:TextFormat) {
  builder.addFieldInt8(3, format, TextFormat.Default);
}

static addTeamSlot(builder:flatbuffers.Builder, teamSlot:TeamSlot) {
  builder.addFieldInt8(4, teamSlot, TeamSlot.Team1);
}

static addTracks(builder:flatbuffers.Builder, tracksOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, tracksOffset, 0);
}

static createTracksVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTracksVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStyle(builder:flatbuffers.Builder, styleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, styleOffset, 0);
}

static endCinematicProp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
