// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CinematicKeyframe } from '../../../blue-bottle-ipc/league-broadcast/cinematics/cinematic-keyframe.js';
import { TrackKind } from '../../../blue-bottle-ipc/league-broadcast/cinematics/track-kind.js';


/**
 * One animated channel of a prop, holding a time-ordered keyframe list.
 */
export class CinematicTrack {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CinematicTrack {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCinematicTrack(bb:flatbuffers.ByteBuffer, obj?:CinematicTrack):CinematicTrack {
  return (obj || new CinematicTrack()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCinematicTrack(bb:flatbuffers.ByteBuffer, obj?:CinematicTrack):CinematicTrack {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CinematicTrack()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():TrackKind {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TrackKind.Position;
}

keys(index: number, obj?:CinematicKeyframe):CinematicKeyframe|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CinematicKeyframe()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

keysLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startCinematicTrack(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKind(builder:flatbuffers.Builder, kind:TrackKind) {
  builder.addFieldInt8(0, kind, TrackKind.Position);
}

static addKeys(builder:flatbuffers.Builder, keysOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, keysOffset, 0);
}

static createKeysVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startKeysVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endCinematicTrack(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCinematicTrack(builder:flatbuffers.Builder, kind:TrackKind, keysOffset:flatbuffers.Offset):flatbuffers.Offset {
  CinematicTrack.startCinematicTrack(builder);
  CinematicTrack.addKind(builder, kind);
  CinematicTrack.addKeys(builder, keysOffset);
  return CinematicTrack.endCinematicTrack(builder);
}
}
