// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Which of League's own render-visibility flags a cinematic keyframes. Exactly the set cinematic
 * playback takes over; the host writes them to the replay render endpoint, lblib is not involved.
 */
export enum CinematicHudElement {
  FloatingText = 0,
  HealthBarChampions = 1,
  HealthBarMinions = 2,
  HealthBarPets = 3,
  HealthBarStructures = 4,
  HealthBarWards = 5,
  FogOfWar = 6,
  InterfaceAll = 7
}
