// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CinematicKeyframe } from '../../../blue-bottle-ipc/league-broadcast/cinematics/cinematic-keyframe.js';


/**
 * One broadcast overlay's visibility over the cinematic, at most one track per overlay.
 * overlay_name is the IngameOverlayRegistry wire name. bool_value is whether that overlay is
 * VISIBLE from the key onwards; the track is stepped (the last key at or before a time wins) and
 * easing is ignored. Between keys the operator's own toggles stand.
 */
export class CinematicOverlayTrack {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CinematicOverlayTrack {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCinematicOverlayTrack(bb:flatbuffers.ByteBuffer, obj?:CinematicOverlayTrack):CinematicOverlayTrack {
  return (obj || new CinematicOverlayTrack()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCinematicOverlayTrack(bb:flatbuffers.ByteBuffer, obj?:CinematicOverlayTrack):CinematicOverlayTrack {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CinematicOverlayTrack()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

overlayName():string|null
overlayName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
overlayName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

keys(index: number, obj?:CinematicKeyframe):CinematicKeyframe|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CinematicKeyframe()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

keysLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startCinematicOverlayTrack(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addOverlayName(builder:flatbuffers.Builder, overlayNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, overlayNameOffset, 0);
}

static addKeys(builder:flatbuffers.Builder, keysOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, keysOffset, 0);
}

static createKeysVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startKeysVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endCinematicOverlayTrack(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCinematicOverlayTrack(builder:flatbuffers.Builder, overlayNameOffset:flatbuffers.Offset, keysOffset:flatbuffers.Offset):flatbuffers.Offset {
  CinematicOverlayTrack.startCinematicOverlayTrack(builder);
  CinematicOverlayTrack.addOverlayName(builder, overlayNameOffset);
  CinematicOverlayTrack.addKeys(builder, keysOffset);
  return CinematicOverlayTrack.endCinematicOverlayTrack(builder);
}
}
