// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Cinematic } from '../../../blue-bottle-ipc/league-broadcast/cinematics/Cinematic.js';


/**
 * Wrapper for list responses.
 */
export class CinematicList {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CinematicList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCinematicList(bb:flatbuffers.ByteBuffer, obj?:CinematicList):CinematicList {
  return (obj || new CinematicList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCinematicList(bb:flatbuffers.ByteBuffer, obj?:CinematicList):CinematicList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CinematicList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cinematics(index: number, obj?:Cinematic):Cinematic|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Cinematic()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

cinematicsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startCinematicList(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addCinematics(builder:flatbuffers.Builder, cinematicsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cinematicsOffset, 0);
}

static createCinematicsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCinematicsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endCinematicList(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCinematicList(builder:flatbuffers.Builder, cinematicsOffset:flatbuffers.Offset):flatbuffers.Offset {
  CinematicList.startCinematicList(builder);
  CinematicList.addCinematics(builder, cinematicsOffset);
  return CinematicList.endCinematicList(builder);
}
}
