// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * One named point on the cinematic timeline. Playback fires it as an outbound event when the clock
 * crosses it; emit_once keeps that to a single fire per playback run, so a rewind that re-crosses
 * the same point stays quiet unless the operator asked for a repeating marker.
 */
export class CinematicMarker {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CinematicMarker {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCinematicMarker(bb:flatbuffers.ByteBuffer, obj?:CinematicMarker):CinematicMarker {
  return (obj || new CinematicMarker()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCinematicMarker(bb:flatbuffers.ByteBuffer, obj?:CinematicMarker):CinematicMarker {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CinematicMarker()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

time():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

emitOnce():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

static startCinematicMarker(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addTime(builder:flatbuffers.Builder, time:number) {
  builder.addFieldFloat32(0, time, 0.0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addEmitOnce(builder:flatbuffers.Builder, emitOnce:boolean) {
  builder.addFieldInt8(2, +emitOnce, +true);
}

static endCinematicMarker(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCinematicMarker(builder:flatbuffers.Builder, time:number, nameOffset:flatbuffers.Offset, emitOnce:boolean):flatbuffers.Offset {
  CinematicMarker.startCinematicMarker(builder);
  CinematicMarker.addTime(builder, time);
  CinematicMarker.addName(builder, nameOffset);
  CinematicMarker.addEmitOnce(builder, emitOnce);
  return CinematicMarker.endCinematicMarker(builder);
}
}
