// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BlendEasing } from '../../../blue-bottle-ipc/league-broadcast/cinematics/blend-easing.js';


/**
 * A single animation keyframe on a track.
 */
export class CinematicKeyframe {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CinematicKeyframe {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCinematicKeyframe(bb:flatbuffers.ByteBuffer, obj?:CinematicKeyframe):CinematicKeyframe {
  return (obj || new CinematicKeyframe()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCinematicKeyframe(bb:flatbuffers.ByteBuffer, obj?:CinematicKeyframe):CinematicKeyframe {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CinematicKeyframe()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

time():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

z():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

floatValue():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

boolValue():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

easing():BlendEasing {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BlendEasing.Linear;
}

static startCinematicKeyframe(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addTime(builder:flatbuffers.Builder, time:number) {
  builder.addFieldFloat32(0, time, 0.0);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldFloat32(1, x, 0.0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldFloat32(2, y, 0.0);
}

static addZ(builder:flatbuffers.Builder, z:number) {
  builder.addFieldFloat32(3, z, 0.0);
}

static addFloatValue(builder:flatbuffers.Builder, floatValue:number) {
  builder.addFieldFloat32(4, floatValue, 0.0);
}

static addBoolValue(builder:flatbuffers.Builder, boolValue:boolean) {
  builder.addFieldInt8(5, +boolValue, +false);
}

static addEasing(builder:flatbuffers.Builder, easing:BlendEasing) {
  builder.addFieldInt8(6, easing, BlendEasing.Linear);
}

static endCinematicKeyframe(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCinematicKeyframe(builder:flatbuffers.Builder, time:number, x:number, y:number, z:number, floatValue:number, boolValue:boolean, easing:BlendEasing):flatbuffers.Offset {
  CinematicKeyframe.startCinematicKeyframe(builder);
  CinematicKeyframe.addTime(builder, time);
  CinematicKeyframe.addX(builder, x);
  CinematicKeyframe.addY(builder, y);
  CinematicKeyframe.addZ(builder, z);
  CinematicKeyframe.addFloatValue(builder, floatValue);
  CinematicKeyframe.addBoolValue(builder, boolValue);
  CinematicKeyframe.addEasing(builder, easing);
  return CinematicKeyframe.endCinematicKeyframe(builder);
}
}
