// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CinematicHudElement } from '../../../blue-bottle-ipc/league-broadcast/cinematics/cinematic-hud-element.js';
import { CinematicKeyframe } from '../../../blue-bottle-ipc/league-broadcast/cinematics/cinematic-keyframe.js';


/**
 * One League-UI element's visibility over the cinematic, at most one track per element.
 * bool_value is whether that element is VISIBLE from the key onwards; the track is stepped (the
 * last key at or before a time wins) and easing is ignored. Where no key covers a time the
 * operator's configured playback default applies instead.
 */
export class CinematicHudTrack {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CinematicHudTrack {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCinematicHudTrack(bb:flatbuffers.ByteBuffer, obj?:CinematicHudTrack):CinematicHudTrack {
  return (obj || new CinematicHudTrack()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCinematicHudTrack(bb:flatbuffers.ByteBuffer, obj?:CinematicHudTrack):CinematicHudTrack {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CinematicHudTrack()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

element():CinematicHudElement {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : CinematicHudElement.FloatingText;
}

keys(index: number, obj?:CinematicKeyframe):CinematicKeyframe|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CinematicKeyframe()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

keysLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startCinematicHudTrack(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addElement(builder:flatbuffers.Builder, element:CinematicHudElement) {
  builder.addFieldInt8(0, element, CinematicHudElement.FloatingText);
}

static addKeys(builder:flatbuffers.Builder, keysOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, keysOffset, 0);
}

static createKeysVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startKeysVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endCinematicHudTrack(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCinematicHudTrack(builder:flatbuffers.Builder, element:CinematicHudElement, keysOffset:flatbuffers.Offset):flatbuffers.Offset {
  CinematicHudTrack.startCinematicHudTrack(builder);
  CinematicHudTrack.addElement(builder, element);
  CinematicHudTrack.addKeys(builder, keysOffset);
  return CinematicHudTrack.endCinematicHudTrack(builder);
}
}
