// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Which playing-roster member within a team a prop is bound to.
 */
export enum PlayerSlot {
  Player1 = 0,
  Player2 = 1,
  Player3 = 2,
  Player4 = 3,
  Player5 = 4
}
