// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Kind of prop entity the host materializes.
 */
export enum PropKind {
  BoundText = 0,
  LogoBillboard = 1
}
