// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Static visual styling for a prop (font from a catalog index; RGBA tint).
 */
export class PropStyle {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PropStyle {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPropStyle(bb:flatbuffers.ByteBuffer, obj?:PropStyle):PropStyle {
  return (obj || new PropStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPropStyle(bb:flatbuffers.ByteBuffer, obj?:PropStyle):PropStyle {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PropStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

fontIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

colorR():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 255;
}

colorG():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 255;
}

colorB():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 255;
}

colorA():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 255;
}

fontSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 32.0;
}

static startPropStyle(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addFontIndex(builder:flatbuffers.Builder, fontIndex:number) {
  builder.addFieldInt32(0, fontIndex, 0);
}

static addColorR(builder:flatbuffers.Builder, colorR:number) {
  builder.addFieldInt8(1, colorR, 255);
}

static addColorG(builder:flatbuffers.Builder, colorG:number) {
  builder.addFieldInt8(2, colorG, 255);
}

static addColorB(builder:flatbuffers.Builder, colorB:number) {
  builder.addFieldInt8(3, colorB, 255);
}

static addColorA(builder:flatbuffers.Builder, colorA:number) {
  builder.addFieldInt8(4, colorA, 255);
}

static addFontSize(builder:flatbuffers.Builder, fontSize:number) {
  builder.addFieldFloat32(5, fontSize, 32.0);
}

static endPropStyle(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPropStyle(builder:flatbuffers.Builder, fontIndex:number, colorR:number, colorG:number, colorB:number, colorA:number, fontSize:number):flatbuffers.Offset {
  PropStyle.startPropStyle(builder);
  PropStyle.addFontIndex(builder, fontIndex);
  PropStyle.addColorR(builder, colorR);
  PropStyle.addColorG(builder, colorG);
  PropStyle.addColorB(builder, colorB);
  PropStyle.addColorA(builder, colorA);
  PropStyle.addFontSize(builder, fontSize);
  return PropStyle.endPropStyle(builder);
}
}
