// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * How an image prop's quad is oriented. FaceCamera re-orients it towards the broadcast camera
 * every frame (its Rotation track is inert); WorldRotation uses the prop's authored rotation.
 */
export enum PropOrientation {
  FaceCamera = 0,
  WorldRotation = 1
}
