// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CinematicTrack } from '../../../blue-bottle-ipc/league-broadcast/cinematics/cinematic-track.js';


export class SetTrackRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SetTrackRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSetTrackRequest(bb:flatbuffers.ByteBuffer, obj?:SetTrackRequest):SetTrackRequest {
  return (obj || new SetTrackRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSetTrackRequest(bb:flatbuffers.ByteBuffer, obj?:SetTrackRequest):SetTrackRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SetTrackRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cinematicId():string|null
cinematicId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cinematicId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

propId():string|null
propId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
propId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

track(obj?:CinematicTrack):CinematicTrack|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new CinematicTrack()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startSetTrackRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addCinematicId(builder:flatbuffers.Builder, cinematicIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cinematicIdOffset, 0);
}

static addPropId(builder:flatbuffers.Builder, propIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, propIdOffset, 0);
}

static addTrack(builder:flatbuffers.Builder, trackOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, trackOffset, 0);
}

static endSetTrackRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
