// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PropStyle } from '../../../blue-bottle-ipc/league-broadcast/cinematics/prop-style.js';


export class SetPropStyleRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SetPropStyleRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSetPropStyleRequest(bb:flatbuffers.ByteBuffer, obj?:SetPropStyleRequest):SetPropStyleRequest {
  return (obj || new SetPropStyleRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSetPropStyleRequest(bb:flatbuffers.ByteBuffer, obj?:SetPropStyleRequest):SetPropStyleRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SetPropStyleRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cinematicId():string|null
cinematicId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cinematicId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

propId():string|null
propId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
propId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

style(obj?:PropStyle):PropStyle|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new PropStyle()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startSetPropStyleRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addCinematicId(builder:flatbuffers.Builder, cinematicIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cinematicIdOffset, 0);
}

static addPropId(builder:flatbuffers.Builder, propIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, propIdOffset, 0);
}

static addStyle(builder:flatbuffers.Builder, styleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, styleOffset, 0);
}

static endSetPropStyleRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
