// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CinematicMarker } from '../../../blue-bottle-ipc/league-broadcast/cinematics/cinematic-marker.js';


export class SetMarkersRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SetMarkersRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSetMarkersRequest(bb:flatbuffers.ByteBuffer, obj?:SetMarkersRequest):SetMarkersRequest {
  return (obj || new SetMarkersRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSetMarkersRequest(bb:flatbuffers.ByteBuffer, obj?:SetMarkersRequest):SetMarkersRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SetMarkersRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cinematicId():string|null
cinematicId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cinematicId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

markers(index: number, obj?:CinematicMarker):CinematicMarker|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CinematicMarker()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

markersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSetMarkersRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCinematicId(builder:flatbuffers.Builder, cinematicIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cinematicIdOffset, 0);
}

static addMarkers(builder:flatbuffers.Builder, markersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, markersOffset, 0);
}

static createMarkersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMarkersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSetMarkersRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSetMarkersRequest(builder:flatbuffers.Builder, cinematicIdOffset:flatbuffers.Offset, markersOffset:flatbuffers.Offset):flatbuffers.Offset {
  SetMarkersRequest.startSetMarkersRequest(builder);
  SetMarkersRequest.addCinematicId(builder, cinematicIdOffset);
  SetMarkersRequest.addMarkers(builder, markersOffset);
  return SetMarkersRequest.endSetMarkersRequest(builder);
}
}
