// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CinematicOverlayTrack } from '../../../blue-bottle-ipc/league-broadcast/cinematics/cinematic-overlay-track.js';


export class SetOverlayTrackRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SetOverlayTrackRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSetOverlayTrackRequest(bb:flatbuffers.ByteBuffer, obj?:SetOverlayTrackRequest):SetOverlayTrackRequest {
  return (obj || new SetOverlayTrackRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSetOverlayTrackRequest(bb:flatbuffers.ByteBuffer, obj?:SetOverlayTrackRequest):SetOverlayTrackRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SetOverlayTrackRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cinematicId():string|null
cinematicId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cinematicId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

track(obj?:CinematicOverlayTrack):CinematicOverlayTrack|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CinematicOverlayTrack()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startSetOverlayTrackRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCinematicId(builder:flatbuffers.Builder, cinematicIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cinematicIdOffset, 0);
}

static addTrack(builder:flatbuffers.Builder, trackOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, trackOffset, 0);
}

static endSetOverlayTrackRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
