// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Which of the two currently-playing teams a prop is bound to.
 */
export enum TeamSlot {
  Team1 = 0,
  Team2 = 1
}
