// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * How a resolved value is formatted into display text.
 */
export enum TextFormat {
  Default = 0,
  Colon = 1,
  Vs = 2
}
