// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Which transform / visibility channel a track animates.
 */
export enum TrackKind {
  Position = 0,
  Rotation = 1,
  Scale = 2,
  Opacity = 3,
  Visible = 4
}
