// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Maps a client-supplied batch index back to the assigned entity_id.
 * client_index is the zero-based index into EntityCreateBatch.items.
 * requested_id is echoed so callers can detect ID-hint collisions
 * (assigned_id != requested_id when the hint could not be honored).
 */
export class EntityAssignment {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EntityAssignment {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEntityAssignment(bb:flatbuffers.ByteBuffer, obj?:EntityAssignment):EntityAssignment {
  return (obj || new EntityAssignment()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEntityAssignment(bb:flatbuffers.ByteBuffer, obj?:EntityAssignment):EntityAssignment {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EntityAssignment()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

clientIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

requestedId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

assignedId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startEntityAssignment(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addClientIndex(builder:flatbuffers.Builder, clientIndex:number) {
  builder.addFieldInt32(0, clientIndex, 0);
}

static addRequestedId(builder:flatbuffers.Builder, requestedId:bigint) {
  builder.addFieldInt64(1, requestedId, BigInt('0'));
}

static addAssignedId(builder:flatbuffers.Builder, assignedId:bigint) {
  builder.addFieldInt64(2, assignedId, BigInt('0'));
}

static endEntityAssignment(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEntityAssignment(builder:flatbuffers.Builder, clientIndex:number, requestedId:bigint, assignedId:bigint):flatbuffers.Offset {
  EntityAssignment.startEntityAssignment(builder);
  EntityAssignment.addClientIndex(builder, clientIndex);
  EntityAssignment.addRequestedId(builder, requestedId);
  EntityAssignment.addAssignedId(builder, assignedId);
  return EntityAssignment.endEntityAssignment(builder);
}
}
