// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ComponentTransform } from '../../../blue-bottle-ipc/league-broadcast/entity/component-transform.js';


/**
 * Throttled transform-only updates emitted during gizmo drag. Carried
 * separately from SceneEntityChanged so the high-frequency drag stream can
 * be bandwidth-tuned without affecting other component updates.
 */
export class EntityTransformUpdate {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EntityTransformUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEntityTransformUpdate(bb:flatbuffers.ByteBuffer, obj?:EntityTransformUpdate):EntityTransformUpdate {
  return (obj || new EntityTransformUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEntityTransformUpdate(bb:flatbuffers.ByteBuffer, obj?:EntityTransformUpdate):EntityTransformUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EntityTransformUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

entityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

transform(obj?:ComponentTransform):ComponentTransform|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ComponentTransform()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startEntityTransformUpdate(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addEntityId(builder:flatbuffers.Builder, entityId:bigint) {
  builder.addFieldInt64(0, entityId, BigInt('0'));
}

static addTransform(builder:flatbuffers.Builder, transformOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, transformOffset, 0);
}

static endEntityTransformUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // transform
  return offset;
}

}
