// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Component, unionToComponent, unionListToComponent } from '../../../blue-bottle-ipc/league-broadcast/entity/Component.js';


/**
 * Create one entity in a scene. Components are typically Transform +
 * Visibility + (one or more renderer kinds) + optional EditState/Script.
 * requested_id is an optional hint for reconnect hydration; lblib will
 * honor it when possible and emit EntityIdChanged otherwise (see scene_events.fbs).
 * client_index is echoed back in the EntityCreated event so the caller can
 * map provisional IDs to assigned IDs when batching.
 */
export class EntityCreate {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EntityCreate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEntityCreate(bb:flatbuffers.ByteBuffer, obj?:EntityCreate):EntityCreate {
  return (obj || new EntityCreate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEntityCreate(bb:flatbuffers.ByteBuffer, obj?:EntityCreate):EntityCreate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EntityCreate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

clientIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

requestedId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

componentsType(index: number):Component|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : null;
}

componentsTypeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

componentsTypeArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

components(index: number, obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__union(obj, this.bb!.__vector(this.bb_pos + offset) + index * 4) : null;
}

componentsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startEntityCreate(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addClientIndex(builder:flatbuffers.Builder, clientIndex:number) {
  builder.addFieldInt32(1, clientIndex, 0);
}

static addRequestedId(builder:flatbuffers.Builder, requestedId:bigint) {
  builder.addFieldInt64(2, requestedId, BigInt('0'));
}

static addComponentsType(builder:flatbuffers.Builder, componentsTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, componentsTypeOffset, 0);
}

static createComponentsTypeVector(builder:flatbuffers.Builder, data:Component[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startComponentsTypeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addComponents(builder:flatbuffers.Builder, componentsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, componentsOffset, 0);
}

static createComponentsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startComponentsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endEntityCreate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEntityCreate(builder:flatbuffers.Builder, sceneId:number, clientIndex:number, requestedId:bigint, componentsTypeOffset:flatbuffers.Offset, componentsOffset:flatbuffers.Offset):flatbuffers.Offset {
  EntityCreate.startEntityCreate(builder);
  EntityCreate.addSceneId(builder, sceneId);
  EntityCreate.addClientIndex(builder, clientIndex);
  EntityCreate.addRequestedId(builder, requestedId);
  EntityCreate.addComponentsType(builder, componentsTypeOffset);
  EntityCreate.addComponents(builder, componentsOffset);
  return EntityCreate.endEntityCreate(builder);
}
}
