// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Discriminator for SceneEntityChanged events. Created / Updated carry the
 * changed components; Destroyed carries no components and uses
 * SceneEntitiesRemoved for the bulk cascade form.
 */
export enum EntityEventKind {
  Created = 0,
  Updated = 1,
  Destroyed = 2,
  Placed = 3
}
