// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Component, unionToComponent, unionListToComponent } from '../../../blue-bottle-ipc/league-broadcast/entity/Component.js';


/**
 * Full property record for one entity — list of all components present.
 * Used by SceneSnapshot (full scene) and as a response to GetComponents
 * (single entity, possibly filtered to a subset of kinds).
 */
export class EntitySnapshot {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EntitySnapshot {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEntitySnapshot(bb:flatbuffers.ByteBuffer, obj?:EntitySnapshot):EntitySnapshot {
  return (obj || new EntitySnapshot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEntitySnapshot(bb:flatbuffers.ByteBuffer, obj?:EntitySnapshot):EntitySnapshot {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EntitySnapshot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

entityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

componentsType(index: number):Component|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : null;
}

componentsTypeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

componentsTypeArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

components(index: number, obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__union(obj, this.bb!.__vector(this.bb_pos + offset) + index * 4) : null;
}

componentsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startEntitySnapshot(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addEntityId(builder:flatbuffers.Builder, entityId:bigint) {
  builder.addFieldInt64(0, entityId, BigInt('0'));
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(1, sceneId, 0);
}

static addComponentsType(builder:flatbuffers.Builder, componentsTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, componentsTypeOffset, 0);
}

static createComponentsTypeVector(builder:flatbuffers.Builder, data:Component[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startComponentsTypeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addComponents(builder:flatbuffers.Builder, componentsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, componentsOffset, 0);
}

static createComponentsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startComponentsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endEntitySnapshot(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEntitySnapshot(builder:flatbuffers.Builder, entityId:bigint, sceneId:number, componentsTypeOffset:flatbuffers.Offset, componentsOffset:flatbuffers.Offset):flatbuffers.Offset {
  EntitySnapshot.startEntitySnapshot(builder);
  EntitySnapshot.addEntityId(builder, entityId);
  EntitySnapshot.addSceneId(builder, sceneId);
  EntitySnapshot.addComponentsType(builder, componentsTypeOffset);
  EntitySnapshot.addComponents(builder, componentsOffset);
  return EntitySnapshot.endEntitySnapshot(builder);
}
}
