// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { EntityCreate } from '../../../blue-bottle-ipc/league-broadcast/scene/entity-create.js';


/**
 * Batched entity creation. Server processes in order, emits one
 * SceneEntitiesAdded event with the assigned IDs.
 */
export class EntityCreateBatch {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EntityCreateBatch {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEntityCreateBatch(bb:flatbuffers.ByteBuffer, obj?:EntityCreateBatch):EntityCreateBatch {
  return (obj || new EntityCreateBatch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEntityCreateBatch(bb:flatbuffers.ByteBuffer, obj?:EntityCreateBatch):EntityCreateBatch {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EntityCreateBatch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

items(index: number, obj?:EntityCreate):EntityCreate|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new EntityCreate()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

itemsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startEntityCreateBatch(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addItems(builder:flatbuffers.Builder, itemsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, itemsOffset, 0);
}

static createItemsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startItemsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endEntityCreateBatch(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEntityCreateBatch(builder:flatbuffers.Builder, sceneId:number, itemsOffset:flatbuffers.Offset):flatbuffers.Offset {
  EntityCreateBatch.startEntityCreateBatch(builder);
  EntityCreateBatch.addSceneId(builder, sceneId);
  EntityCreateBatch.addItems(builder, itemsOffset);
  return EntityCreateBatch.endEntityCreateBatch(builder);
}
}
