// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ComponentKind } from '../../../blue-bottle-ipc/league-broadcast/entity/component-kind.js';


/**
 * Query components on one entity. Empty `kinds` returns the full bag.
 * Response is delivered as a SceneEntitiesSnapshot event with one entry.
 */
export class GetComponents {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetComponents {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetComponents(bb:flatbuffers.ByteBuffer, obj?:GetComponents):GetComponents {
  return (obj || new GetComponents()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetComponents(bb:flatbuffers.ByteBuffer, obj?:GetComponents):GetComponents {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetComponents()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

entityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

kinds(index: number):ComponentKind|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

kindsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

kindsArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startGetComponents(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addEntityId(builder:flatbuffers.Builder, entityId:bigint) {
  builder.addFieldInt64(0, entityId, BigInt('0'));
}

static addKinds(builder:flatbuffers.Builder, kindsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, kindsOffset, 0);
}

static createKindsVector(builder:flatbuffers.Builder, data:ComponentKind[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startKindsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endGetComponents(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetComponents(builder:flatbuffers.Builder, entityId:bigint, kindsOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetComponents.startGetComponents(builder);
  GetComponents.addEntityId(builder, entityId);
  GetComponents.addKinds(builder, kindsOffset);
  return GetComponents.endGetComponents(builder);
}
}
