// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Exact lifecycle of an entity-gizmo manipulation. None preserves the legacy meaning for
 * transform streams produced by direct dragging or older clients.
 */
export enum GizmoManipulationPhase {
  None = 0,
  Begin = 1,
  Update = 2,
  Commit = 3
}
