// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ComponentKind } from '../../../blue-bottle-ipc/league-broadcast/entity/component-kind.js';


/**
 * Remove one component (by kind) from one entity. Removing a renderer
 * component stops that entity from being drawn by that system; removing
 * Transform / Visibility is rejected (they are required on every entity).
 */
export class RemoveComponent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RemoveComponent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRemoveComponent(bb:flatbuffers.ByteBuffer, obj?:RemoveComponent):RemoveComponent {
  return (obj || new RemoveComponent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRemoveComponent(bb:flatbuffers.ByteBuffer, obj?:RemoveComponent):RemoveComponent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RemoveComponent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

entityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

kind():ComponentKind {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ComponentKind.Transform;
}

static startRemoveComponent(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addEntityId(builder:flatbuffers.Builder, entityId:bigint) {
  builder.addFieldInt64(0, entityId, BigInt('0'));
}

static addKind(builder:flatbuffers.Builder, kind:ComponentKind) {
  builder.addFieldInt8(1, kind, ComponentKind.Transform);
}

static endRemoveComponent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRemoveComponent(builder:flatbuffers.Builder, entityId:bigint, kind:ComponentKind):flatbuffers.Offset {
  RemoveComponent.startRemoveComponent(builder);
  RemoveComponent.addEntityId(builder, entityId);
  RemoveComponent.addKind(builder, kind);
  return RemoveComponent.endRemoveComponent(builder);
}
}
