// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Toggle the render visibility of a scene (entities stay loaded).
 */
export class SceneSetVisibility {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneSetVisibility {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneSetVisibility(bb:flatbuffers.ByteBuffer, obj?:SceneSetVisibility):SceneSetVisibility {
  return (obj || new SceneSetVisibility()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneSetVisibility(bb:flatbuffers.ByteBuffer, obj?:SceneSetVisibility):SceneSetVisibility {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneSetVisibility()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

visible():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startSceneSetVisibility(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addVisible(builder:flatbuffers.Builder, visible:boolean) {
  builder.addFieldInt8(1, +visible, +false);
}

static endSceneSetVisibility(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneSetVisibility(builder:flatbuffers.Builder, sceneId:number, visible:boolean):flatbuffers.Offset {
  SceneSetVisibility.startSceneSetVisibility(builder);
  SceneSetVisibility.addSceneId(builder, sceneId);
  SceneSetVisibility.addVisible(builder, visible);
  return SceneSetVisibility.endSceneSetVisibility(builder);
}
}
