// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SceneDescriptor } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-descriptor.js';


/**
 * Emitted when a SceneCreate command succeeds.
 */
export class SceneCreated {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneCreated {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneCreated(bb:flatbuffers.ByteBuffer, obj?:SceneCreated):SceneCreated {
  return (obj || new SceneCreated()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneCreated(bb:flatbuffers.ByteBuffer, obj?:SceneCreated):SceneCreated {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneCreated()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

scene(obj?:SceneDescriptor):SceneDescriptor|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SceneDescriptor()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startSceneCreated(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addScene(builder:flatbuffers.Builder, sceneOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, sceneOffset, 0);
}

static endSceneCreated(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // scene
  return offset;
}

static createSceneCreated(builder:flatbuffers.Builder, sceneOffset:flatbuffers.Offset):flatbuffers.Offset {
  SceneCreated.startSceneCreated(builder);
  SceneCreated.addScene(builder, sceneOffset);
  return SceneCreated.endSceneCreated(builder);
}
}
