// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SceneDescriptor } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-descriptor.js';


/**
 * Emitted whenever visibility, editable, or z_order changes on any scene.
 */
export class SceneStateChanged {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneStateChanged {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneStateChanged(bb:flatbuffers.ByteBuffer, obj?:SceneStateChanged):SceneStateChanged {
  return (obj || new SceneStateChanged()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneStateChanged(bb:flatbuffers.ByteBuffer, obj?:SceneStateChanged):SceneStateChanged {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneStateChanged()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

scene(obj?:SceneDescriptor):SceneDescriptor|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SceneDescriptor()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startSceneStateChanged(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addScene(builder:flatbuffers.Builder, sceneOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, sceneOffset, 0);
}

static endSceneStateChanged(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // scene
  return offset;
}

static createSceneStateChanged(builder:flatbuffers.Builder, sceneOffset:flatbuffers.Offset):flatbuffers.Offset {
  SceneStateChanged.startSceneStateChanged(builder);
  SceneStateChanged.addScene(builder, sceneOffset);
  return SceneStateChanged.endSceneStateChanged(builder);
}
}
