// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Emitted when a scene is fully unloaded and its ID freed.
 */
export class SceneUnloaded {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneUnloaded {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneUnloaded(bb:flatbuffers.ByteBuffer, obj?:SceneUnloaded):SceneUnloaded {
  return (obj || new SceneUnloaded()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneUnloaded(bb:flatbuffers.ByteBuffer, obj?:SceneUnloaded):SceneUnloaded {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneUnloaded()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSceneUnloaded(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static endSceneUnloaded(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneUnloaded(builder:flatbuffers.Builder, sceneId:number, nameOffset:flatbuffers.Offset):flatbuffers.Offset {
  SceneUnloaded.startSceneUnloaded(builder);
  SceneUnloaded.addSceneId(builder, sceneId);
  SceneUnloaded.addName(builder, nameOffset);
  return SceneUnloaded.endSceneUnloaded(builder);
}
}
