// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Permanently destroy a scene and all its entities.
 * Cascades: all children of every entity in the scene are also destroyed.
 */
export class SceneUnload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneUnload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneUnload(bb:flatbuffers.ByteBuffer, obj?:SceneUnload):SceneUnload {
  return (obj || new SceneUnload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneUnload(bb:flatbuffers.ByteBuffer, obj?:SceneUnload):SceneUnload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneUnload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startSceneUnload(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static endSceneUnload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneUnload(builder:flatbuffers.Builder, sceneId:number):flatbuffers.Offset {
  SceneUnload.startSceneUnload(builder);
  SceneUnload.addSceneId(builder, sceneId);
  return SceneUnload.endSceneUnload(builder);
}
}
