// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ScriptLogLevel } from '../../../blue-bottle-ipc/league-broadcast/scene/script-log-level.js';


/**
 * Emitted when a Lua script calls log.print/info/warn/error.
 */
export class SceneScriptLog {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneScriptLog {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneScriptLog(bb:flatbuffers.ByteBuffer, obj?:SceneScriptLog):SceneScriptLog {
  return (obj || new SceneScriptLog()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneScriptLog(bb:flatbuffers.ByteBuffer, obj?:SceneScriptLog):SceneScriptLog {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneScriptLog()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

entityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

scriptName():string|null
scriptName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
scriptName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

level():ScriptLogLevel {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ScriptLogLevel.Info;
}

static startSceneScriptLog(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addEntityId(builder:flatbuffers.Builder, entityId:bigint) {
  builder.addFieldInt64(1, entityId, BigInt('0'));
}

static addScriptName(builder:flatbuffers.Builder, scriptNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, scriptNameOffset, 0);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, messageOffset, 0);
}

static addLevel(builder:flatbuffers.Builder, level:ScriptLogLevel) {
  builder.addFieldInt8(4, level, ScriptLogLevel.Info);
}

static endSceneScriptLog(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneScriptLog(builder:flatbuffers.Builder, sceneId:number, entityId:bigint, scriptNameOffset:flatbuffers.Offset, messageOffset:flatbuffers.Offset, level:ScriptLogLevel):flatbuffers.Offset {
  SceneScriptLog.startSceneScriptLog(builder);
  SceneScriptLog.addSceneId(builder, sceneId);
  SceneScriptLog.addEntityId(builder, entityId);
  SceneScriptLog.addScriptName(builder, scriptNameOffset);
  SceneScriptLog.addMessage(builder, messageOffset);
  SceneScriptLog.addLevel(builder, level);
  return SceneScriptLog.endSceneScriptLog(builder);
}
}
