// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Change the render z-order of a scene (ascending = drawn first / behind).
 */
export class SceneSetZOrder {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneSetZOrder {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneSetZOrder(bb:flatbuffers.ByteBuffer, obj?:SceneSetZOrder):SceneSetZOrder {
  return (obj || new SceneSetZOrder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneSetZOrder(bb:flatbuffers.ByteBuffer, obj?:SceneSetZOrder):SceneSetZOrder {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneSetZOrder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

zOrder():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startSceneSetZOrder(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addZOrder(builder:flatbuffers.Builder, zOrder:number) {
  builder.addFieldInt32(1, zOrder, 0);
}

static endSceneSetZOrder(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneSetZOrder(builder:flatbuffers.Builder, sceneId:number, zOrder:number):flatbuffers.Offset {
  SceneSetZOrder.startSceneSetZOrder(builder);
  SceneSetZOrder.addSceneId(builder, sceneId);
  SceneSetZOrder.addZOrder(builder, zOrder);
  return SceneSetZOrder.endSceneSetZOrder(builder);
}
}
