// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { SceneCreated } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-created.js';
import { SceneEntitiesAdded } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-entities-added.js';
import { SceneEntitiesRemoved } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-entities-removed.js';
import { SceneEntitiesSnapshot } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-entities-snapshot.js';
import { SceneEntityChanged } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-entity-changed.js';
import { SceneEntityIdChanged } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-entity-id-changed.js';
import { SceneEntityTransformUpdates } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-entity-transform-updates.js';
import { SceneList } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-list.js';
import { SceneScriptError } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-script-error.js';
import { SceneScriptLog } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-script-log.js';
import { SceneSelectionChanged } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-selection-changed.js';
import { SceneSnapshot } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-snapshot.js';
import { SceneStateChanged } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-state-changed.js';
import { SceneUnloaded } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-unloaded.js';
import { ScriptAssetChanged } from '../../../blue-bottle-ipc/league-broadcast/scene/script-asset-changed.js';
import { ScriptAssetDeleted } from '../../../blue-bottle-ipc/league-broadcast/scene/script-asset-deleted.js';
import { ScriptLibrary } from '../../../blue-bottle-ipc/league-broadcast/scene/script-library.js';


export enum SceneEvent {
  NONE = 0,
  SceneCreated = 1,
  SceneUnloaded = 2,
  SceneStateChanged = 3,
  SceneList = 4,
  SceneSnapshot = 5,
  SceneEntitiesAdded = 6,
  SceneEntitiesRemoved = 7,
  SceneEntitiesSnapshot = 8,
  SceneEntityChanged = 9,
  SceneEntityTransformUpdates = 10,
  SceneSelectionChanged = 11,
  SceneEntityIdChanged = 12,
  SceneScriptError = 13,
  SceneScriptLog = 14,
  ScriptAssetChanged = 15,
  ScriptAssetDeleted = 16,
  ScriptLibrary = 17
}

export function unionToSceneEvent(
  type: SceneEvent,
  accessor: (obj:SceneCreated|SceneEntitiesAdded|SceneEntitiesRemoved|SceneEntitiesSnapshot|SceneEntityChanged|SceneEntityIdChanged|SceneEntityTransformUpdates|SceneList|SceneScriptError|SceneScriptLog|SceneSelectionChanged|SceneSnapshot|SceneStateChanged|SceneUnloaded|ScriptAssetChanged|ScriptAssetDeleted|ScriptLibrary) => SceneCreated|SceneEntitiesAdded|SceneEntitiesRemoved|SceneEntitiesSnapshot|SceneEntityChanged|SceneEntityIdChanged|SceneEntityTransformUpdates|SceneList|SceneScriptError|SceneScriptLog|SceneSelectionChanged|SceneSnapshot|SceneStateChanged|SceneUnloaded|ScriptAssetChanged|ScriptAssetDeleted|ScriptLibrary|null
): SceneCreated|SceneEntitiesAdded|SceneEntitiesRemoved|SceneEntitiesSnapshot|SceneEntityChanged|SceneEntityIdChanged|SceneEntityTransformUpdates|SceneList|SceneScriptError|SceneScriptLog|SceneSelectionChanged|SceneSnapshot|SceneStateChanged|SceneUnloaded|ScriptAssetChanged|ScriptAssetDeleted|ScriptLibrary|null {
  switch(SceneEvent[type]) {
    case 'NONE': return null; 
    case 'SceneCreated': return accessor(new SceneCreated())! as SceneCreated;
    case 'SceneUnloaded': return accessor(new SceneUnloaded())! as SceneUnloaded;
    case 'SceneStateChanged': return accessor(new SceneStateChanged())! as SceneStateChanged;
    case 'SceneList': return accessor(new SceneList())! as SceneList;
    case 'SceneSnapshot': return accessor(new SceneSnapshot())! as SceneSnapshot;
    case 'SceneEntitiesAdded': return accessor(new SceneEntitiesAdded())! as SceneEntitiesAdded;
    case 'SceneEntitiesRemoved': return accessor(new SceneEntitiesRemoved())! as SceneEntitiesRemoved;
    case 'SceneEntitiesSnapshot': return accessor(new SceneEntitiesSnapshot())! as SceneEntitiesSnapshot;
    case 'SceneEntityChanged': return accessor(new SceneEntityChanged())! as SceneEntityChanged;
    case 'SceneEntityTransformUpdates': return accessor(new SceneEntityTransformUpdates())! as SceneEntityTransformUpdates;
    case 'SceneSelectionChanged': return accessor(new SceneSelectionChanged())! as SceneSelectionChanged;
    case 'SceneEntityIdChanged': return accessor(new SceneEntityIdChanged())! as SceneEntityIdChanged;
    case 'SceneScriptError': return accessor(new SceneScriptError())! as SceneScriptError;
    case 'SceneScriptLog': return accessor(new SceneScriptLog())! as SceneScriptLog;
    case 'ScriptAssetChanged': return accessor(new ScriptAssetChanged())! as ScriptAssetChanged;
    case 'ScriptAssetDeleted': return accessor(new ScriptAssetDeleted())! as ScriptAssetDeleted;
    case 'ScriptLibrary': return accessor(new ScriptLibrary())! as ScriptLibrary;
    default: return null;
  }
}

export function unionListToSceneEvent(
  type: SceneEvent, 
  accessor: (index: number, obj:SceneCreated|SceneEntitiesAdded|SceneEntitiesRemoved|SceneEntitiesSnapshot|SceneEntityChanged|SceneEntityIdChanged|SceneEntityTransformUpdates|SceneList|SceneScriptError|SceneScriptLog|SceneSelectionChanged|SceneSnapshot|SceneStateChanged|SceneUnloaded|ScriptAssetChanged|ScriptAssetDeleted|ScriptLibrary) => SceneCreated|SceneEntitiesAdded|SceneEntitiesRemoved|SceneEntitiesSnapshot|SceneEntityChanged|SceneEntityIdChanged|SceneEntityTransformUpdates|SceneList|SceneScriptError|SceneScriptLog|SceneSelectionChanged|SceneSnapshot|SceneStateChanged|SceneUnloaded|ScriptAssetChanged|ScriptAssetDeleted|ScriptLibrary|null, 
  index: number
): SceneCreated|SceneEntitiesAdded|SceneEntitiesRemoved|SceneEntitiesSnapshot|SceneEntityChanged|SceneEntityIdChanged|SceneEntityTransformUpdates|SceneList|SceneScriptError|SceneScriptLog|SceneSelectionChanged|SceneSnapshot|SceneStateChanged|SceneUnloaded|ScriptAssetChanged|ScriptAssetDeleted|ScriptLibrary|null {
  switch(SceneEvent[type]) {
    case 'NONE': return null; 
    case 'SceneCreated': return accessor(index, new SceneCreated())! as SceneCreated;
    case 'SceneUnloaded': return accessor(index, new SceneUnloaded())! as SceneUnloaded;
    case 'SceneStateChanged': return accessor(index, new SceneStateChanged())! as SceneStateChanged;
    case 'SceneList': return accessor(index, new SceneList())! as SceneList;
    case 'SceneSnapshot': return accessor(index, new SceneSnapshot())! as SceneSnapshot;
    case 'SceneEntitiesAdded': return accessor(index, new SceneEntitiesAdded())! as SceneEntitiesAdded;
    case 'SceneEntitiesRemoved': return accessor(index, new SceneEntitiesRemoved())! as SceneEntitiesRemoved;
    case 'SceneEntitiesSnapshot': return accessor(index, new SceneEntitiesSnapshot())! as SceneEntitiesSnapshot;
    case 'SceneEntityChanged': return accessor(index, new SceneEntityChanged())! as SceneEntityChanged;
    case 'SceneEntityTransformUpdates': return accessor(index, new SceneEntityTransformUpdates())! as SceneEntityTransformUpdates;
    case 'SceneSelectionChanged': return accessor(index, new SceneSelectionChanged())! as SceneSelectionChanged;
    case 'SceneEntityIdChanged': return accessor(index, new SceneEntityIdChanged())! as SceneEntityIdChanged;
    case 'SceneScriptError': return accessor(index, new SceneScriptError())! as SceneScriptError;
    case 'SceneScriptLog': return accessor(index, new SceneScriptLog())! as SceneScriptLog;
    case 'ScriptAssetChanged': return accessor(index, new ScriptAssetChanged())! as ScriptAssetChanged;
    case 'ScriptAssetDeleted': return accessor(index, new ScriptAssetDeleted())! as ScriptAssetDeleted;
    case 'ScriptLibrary': return accessor(index, new ScriptLibrary())! as ScriptLibrary;
    default: return null;
  }
}
