// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { EntityAssignment } from '../../../blue-bottle-ipc/league-broadcast/scene/entity-assignment.js';


/**
 * Emitted after EntityCreateBatch with one assignment per created entity.
 */
export class SceneEntitiesAdded {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneEntitiesAdded {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneEntitiesAdded(bb:flatbuffers.ByteBuffer, obj?:SceneEntitiesAdded):SceneEntitiesAdded {
  return (obj || new SceneEntitiesAdded()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneEntitiesAdded(bb:flatbuffers.ByteBuffer, obj?:SceneEntitiesAdded):SceneEntitiesAdded {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneEntitiesAdded()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

assignments(index: number, obj?:EntityAssignment):EntityAssignment|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new EntityAssignment()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

assignmentsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSceneEntitiesAdded(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addAssignments(builder:flatbuffers.Builder, assignmentsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, assignmentsOffset, 0);
}

static createAssignmentsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startAssignmentsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSceneEntitiesAdded(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneEntitiesAdded(builder:flatbuffers.Builder, sceneId:number, assignmentsOffset:flatbuffers.Offset):flatbuffers.Offset {
  SceneEntitiesAdded.startSceneEntitiesAdded(builder);
  SceneEntitiesAdded.addSceneId(builder, sceneId);
  SceneEntitiesAdded.addAssignments(builder, assignmentsOffset);
  return SceneEntitiesAdded.endSceneEntitiesAdded(builder);
}
}
