// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Summary descriptor of one scene, used in SceneList and SceneCreated /
 * SceneStateChanged.
 */
export class SceneDescriptor {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneDescriptor {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneDescriptor(bb:flatbuffers.ByteBuffer, obj?:SceneDescriptor):SceneDescriptor {
  return (obj || new SceneDescriptor()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneDescriptor(bb:flatbuffers.ByteBuffer, obj?:SceneDescriptor):SceneDescriptor {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneDescriptor()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

visible():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

editable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

zOrder():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

entityCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

/**
 * Stable hash of full scene state. C# uses this to skip snapshot transfer on reconnect.
 */
fingerprint():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startSceneDescriptor(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addVisible(builder:flatbuffers.Builder, visible:boolean) {
  builder.addFieldInt8(2, +visible, +true);
}

static addEditable(builder:flatbuffers.Builder, editable:boolean) {
  builder.addFieldInt8(3, +editable, +false);
}

static addZOrder(builder:flatbuffers.Builder, zOrder:number) {
  builder.addFieldInt32(4, zOrder, 0);
}

static addEntityCount(builder:flatbuffers.Builder, entityCount:number) {
  builder.addFieldInt32(5, entityCount, 0);
}

static addFingerprint(builder:flatbuffers.Builder, fingerprint:bigint) {
  builder.addFieldInt64(6, fingerprint, BigInt('0'));
}

static endSceneDescriptor(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneDescriptor(builder:flatbuffers.Builder, sceneId:number, nameOffset:flatbuffers.Offset, visible:boolean, editable:boolean, zOrder:number, entityCount:number, fingerprint:bigint):flatbuffers.Offset {
  SceneDescriptor.startSceneDescriptor(builder);
  SceneDescriptor.addSceneId(builder, sceneId);
  SceneDescriptor.addName(builder, nameOffset);
  SceneDescriptor.addVisible(builder, visible);
  SceneDescriptor.addEditable(builder, editable);
  SceneDescriptor.addZOrder(builder, zOrder);
  SceneDescriptor.addEntityCount(builder, entityCount);
  SceneDescriptor.addFingerprint(builder, fingerprint);
  return SceneDescriptor.endSceneDescriptor(builder);
}
}
