// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { EntityTransformUpdate } from '../../../blue-bottle-ipc/league-broadcast/scene/entity-transform-update.js';


export class SceneEntityTransformUpdates {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneEntityTransformUpdates {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneEntityTransformUpdates(bb:flatbuffers.ByteBuffer, obj?:SceneEntityTransformUpdates):SceneEntityTransformUpdates {
  return (obj || new SceneEntityTransformUpdates()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneEntityTransformUpdates(bb:flatbuffers.ByteBuffer, obj?:SceneEntityTransformUpdates):SceneEntityTransformUpdates {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneEntityTransformUpdates()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

updates(index: number, obj?:EntityTransformUpdate):EntityTransformUpdate|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new EntityTransformUpdate()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

updatesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSceneEntityTransformUpdates(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addUpdates(builder:flatbuffers.Builder, updatesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, updatesOffset, 0);
}

static createUpdatesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startUpdatesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSceneEntityTransformUpdates(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneEntityTransformUpdates(builder:flatbuffers.Builder, sceneId:number, updatesOffset:flatbuffers.Offset):flatbuffers.Offset {
  SceneEntityTransformUpdates.startSceneEntityTransformUpdates(builder);
  SceneEntityTransformUpdates.addSceneId(builder, sceneId);
  SceneEntityTransformUpdates.addUpdates(builder, updatesOffset);
  return SceneEntityTransformUpdates.endSceneEntityTransformUpdates(builder);
}
}
