// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Emitted whenever the selection set for a scene changes — from a click,
 * a modifier-key click, or a SceneSetSelection command.
 */
export class SceneSelectionChanged {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneSelectionChanged {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneSelectionChanged(bb:flatbuffers.ByteBuffer, obj?:SceneSelectionChanged):SceneSelectionChanged {
  return (obj || new SceneSelectionChanged()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneSelectionChanged(bb:flatbuffers.ByteBuffer, obj?:SceneSelectionChanged):SceneSelectionChanged {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneSelectionChanged()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

selectedEntityIds(index: number):bigint|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb!.__vector(this.bb_pos + offset) + index * 8) : BigInt(0);
}

selectedEntityIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSceneSelectionChanged(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addSelectedEntityIds(builder:flatbuffers.Builder, selectedEntityIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, selectedEntityIdsOffset, 0);
}

static createSelectedEntityIdsVector(builder:flatbuffers.Builder, data:bigint[]):flatbuffers.Offset {
  builder.startVector(8, data.length, 8);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]!);
  }
  return builder.endVector();
}

static startSelectedEntityIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 8);
}

static endSceneSelectionChanged(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneSelectionChanged(builder:flatbuffers.Builder, sceneId:number, selectedEntityIdsOffset:flatbuffers.Offset):flatbuffers.Offset {
  SceneSelectionChanged.startSceneSelectionChanged(builder);
  SceneSelectionChanged.addSceneId(builder, sceneId);
  SceneSelectionChanged.addSelectedEntityIds(builder, selectedEntityIdsOffset);
  return SceneSelectionChanged.endSceneSelectionChanged(builder);
}
}
