// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Component, unionToComponent, unionListToComponent } from '../../../blue-bottle-ipc/league-broadcast/entity/Component.js';
import { EntityEventKind } from '../../../blue-bottle-ipc/league-broadcast/scene/entity-event-kind.js';


/**
 * Per-entity change event. Fires on SetComponent, RemoveComponent, and on
 * in-editor manipulations (gizmo drag end, click-to-place, parent-by-drag).
 * changed_components is empty for Destroyed; for Placed it carries the final
 * Transform component (mirrors the old SceneObjectPlaced flow).
 */
export class SceneEntityChanged {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneEntityChanged {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneEntityChanged(bb:flatbuffers.ByteBuffer, obj?:SceneEntityChanged):SceneEntityChanged {
  return (obj || new SceneEntityChanged()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneEntityChanged(bb:flatbuffers.ByteBuffer, obj?:SceneEntityChanged):SceneEntityChanged {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneEntityChanged()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():EntityEventKind {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : EntityEventKind.Created;
}

entityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

changedComponentsType(index: number):Component|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : null;
}

changedComponentsTypeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

changedComponentsTypeArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

changedComponents(index: number, obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__union(obj, this.bb!.__vector(this.bb_pos + offset) + index * 4) : null;
}

changedComponentsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSceneEntityChanged(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addKind(builder:flatbuffers.Builder, kind:EntityEventKind) {
  builder.addFieldInt8(0, kind, EntityEventKind.Created);
}

static addEntityId(builder:flatbuffers.Builder, entityId:bigint) {
  builder.addFieldInt64(1, entityId, BigInt('0'));
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(2, sceneId, 0);
}

static addChangedComponentsType(builder:flatbuffers.Builder, changedComponentsTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, changedComponentsTypeOffset, 0);
}

static createChangedComponentsTypeVector(builder:flatbuffers.Builder, data:Component[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startChangedComponentsTypeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addChangedComponents(builder:flatbuffers.Builder, changedComponentsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, changedComponentsOffset, 0);
}

static createChangedComponentsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startChangedComponentsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSceneEntityChanged(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneEntityChanged(builder:flatbuffers.Builder, kind:EntityEventKind, entityId:bigint, sceneId:number, changedComponentsTypeOffset:flatbuffers.Offset, changedComponentsOffset:flatbuffers.Offset):flatbuffers.Offset {
  SceneEntityChanged.startSceneEntityChanged(builder);
  SceneEntityChanged.addKind(builder, kind);
  SceneEntityChanged.addEntityId(builder, entityId);
  SceneEntityChanged.addSceneId(builder, sceneId);
  SceneEntityChanged.addChangedComponentsType(builder, changedComponentsTypeOffset);
  SceneEntityChanged.addChangedComponents(builder, changedComponentsOffset);
  return SceneEntityChanged.endSceneEntityChanged(builder);
}
}
