// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { EntityCreateBatch } from '../../../blue-bottle-ipc/league-broadcast/scene/entity-create-batch.js';
import { EntityDestroy } from '../../../blue-bottle-ipc/league-broadcast/scene/entity-destroy.js';
import { GetComponents } from '../../../blue-bottle-ipc/league-broadcast/scene/get-components.js';
import { RemoveComponent } from '../../../blue-bottle-ipc/league-broadcast/scene/remove-component.js';
import { SceneCreate } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-create.js';
import { SceneListRequest } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-list-request.js';
import { SceneSetEditable } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-set-editable.js';
import { SceneSetSelection } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-set-selection.js';
import { SceneSetVisibility } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-set-visibility.js';
import { SceneSetZOrder } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-set-zorder.js';
import { SceneSnapshotRequest } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-snapshot-request.js';
import { SceneUnload } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-unload.js';
import { ScriptCreate } from '../../../blue-bottle-ipc/league-broadcast/scene/script-create.js';
import { ScriptDelete } from '../../../blue-bottle-ipc/league-broadcast/scene/script-delete.js';
import { ScriptListRequest } from '../../../blue-bottle-ipc/league-broadcast/scene/script-list-request.js';
import { ScriptUpdate } from '../../../blue-bottle-ipc/league-broadcast/scene/script-update.js';
import { SetComponentBatch } from '../../../blue-bottle-ipc/league-broadcast/scene/set-component-batch.js';


export enum SceneCommand {
  NONE = 0,
  SceneCreate = 1,
  SceneUnload = 2,
  SceneSetVisibility = 3,
  SceneSetEditable = 4,
  SceneSetZOrder = 5,
  SceneListRequest = 6,
  SceneSnapshotRequest = 7,
  SceneSetSelection = 8,
  EntityCreateBatch = 9,
  EntityDestroy = 10,
  SetComponentBatch = 11,
  RemoveComponent = 12,
  GetComponents = 13,
  ScriptCreate = 14,
  ScriptUpdate = 15,
  ScriptDelete = 16,
  ScriptListRequest = 17
}

export function unionToSceneCommand(
  type: SceneCommand,
  accessor: (obj:EntityCreateBatch|EntityDestroy|GetComponents|RemoveComponent|SceneCreate|SceneListRequest|SceneSetEditable|SceneSetSelection|SceneSetVisibility|SceneSetZOrder|SceneSnapshotRequest|SceneUnload|ScriptCreate|ScriptDelete|ScriptListRequest|ScriptUpdate|SetComponentBatch) => EntityCreateBatch|EntityDestroy|GetComponents|RemoveComponent|SceneCreate|SceneListRequest|SceneSetEditable|SceneSetSelection|SceneSetVisibility|SceneSetZOrder|SceneSnapshotRequest|SceneUnload|ScriptCreate|ScriptDelete|ScriptListRequest|ScriptUpdate|SetComponentBatch|null
): EntityCreateBatch|EntityDestroy|GetComponents|RemoveComponent|SceneCreate|SceneListRequest|SceneSetEditable|SceneSetSelection|SceneSetVisibility|SceneSetZOrder|SceneSnapshotRequest|SceneUnload|ScriptCreate|ScriptDelete|ScriptListRequest|ScriptUpdate|SetComponentBatch|null {
  switch(SceneCommand[type]) {
    case 'NONE': return null; 
    case 'SceneCreate': return accessor(new SceneCreate())! as SceneCreate;
    case 'SceneUnload': return accessor(new SceneUnload())! as SceneUnload;
    case 'SceneSetVisibility': return accessor(new SceneSetVisibility())! as SceneSetVisibility;
    case 'SceneSetEditable': return accessor(new SceneSetEditable())! as SceneSetEditable;
    case 'SceneSetZOrder': return accessor(new SceneSetZOrder())! as SceneSetZOrder;
    case 'SceneListRequest': return accessor(new SceneListRequest())! as SceneListRequest;
    case 'SceneSnapshotRequest': return accessor(new SceneSnapshotRequest())! as SceneSnapshotRequest;
    case 'SceneSetSelection': return accessor(new SceneSetSelection())! as SceneSetSelection;
    case 'EntityCreateBatch': return accessor(new EntityCreateBatch())! as EntityCreateBatch;
    case 'EntityDestroy': return accessor(new EntityDestroy())! as EntityDestroy;
    case 'SetComponentBatch': return accessor(new SetComponentBatch())! as SetComponentBatch;
    case 'RemoveComponent': return accessor(new RemoveComponent())! as RemoveComponent;
    case 'GetComponents': return accessor(new GetComponents())! as GetComponents;
    case 'ScriptCreate': return accessor(new ScriptCreate())! as ScriptCreate;
    case 'ScriptUpdate': return accessor(new ScriptUpdate())! as ScriptUpdate;
    case 'ScriptDelete': return accessor(new ScriptDelete())! as ScriptDelete;
    case 'ScriptListRequest': return accessor(new ScriptListRequest())! as ScriptListRequest;
    default: return null;
  }
}

export function unionListToSceneCommand(
  type: SceneCommand, 
  accessor: (index: number, obj:EntityCreateBatch|EntityDestroy|GetComponents|RemoveComponent|SceneCreate|SceneListRequest|SceneSetEditable|SceneSetSelection|SceneSetVisibility|SceneSetZOrder|SceneSnapshotRequest|SceneUnload|ScriptCreate|ScriptDelete|ScriptListRequest|ScriptUpdate|SetComponentBatch) => EntityCreateBatch|EntityDestroy|GetComponents|RemoveComponent|SceneCreate|SceneListRequest|SceneSetEditable|SceneSetSelection|SceneSetVisibility|SceneSetZOrder|SceneSnapshotRequest|SceneUnload|ScriptCreate|ScriptDelete|ScriptListRequest|ScriptUpdate|SetComponentBatch|null, 
  index: number
): EntityCreateBatch|EntityDestroy|GetComponents|RemoveComponent|SceneCreate|SceneListRequest|SceneSetEditable|SceneSetSelection|SceneSetVisibility|SceneSetZOrder|SceneSnapshotRequest|SceneUnload|ScriptCreate|ScriptDelete|ScriptListRequest|ScriptUpdate|SetComponentBatch|null {
  switch(SceneCommand[type]) {
    case 'NONE': return null; 
    case 'SceneCreate': return accessor(index, new SceneCreate())! as SceneCreate;
    case 'SceneUnload': return accessor(index, new SceneUnload())! as SceneUnload;
    case 'SceneSetVisibility': return accessor(index, new SceneSetVisibility())! as SceneSetVisibility;
    case 'SceneSetEditable': return accessor(index, new SceneSetEditable())! as SceneSetEditable;
    case 'SceneSetZOrder': return accessor(index, new SceneSetZOrder())! as SceneSetZOrder;
    case 'SceneListRequest': return accessor(index, new SceneListRequest())! as SceneListRequest;
    case 'SceneSnapshotRequest': return accessor(index, new SceneSnapshotRequest())! as SceneSnapshotRequest;
    case 'SceneSetSelection': return accessor(index, new SceneSetSelection())! as SceneSetSelection;
    case 'EntityCreateBatch': return accessor(index, new EntityCreateBatch())! as EntityCreateBatch;
    case 'EntityDestroy': return accessor(index, new EntityDestroy())! as EntityDestroy;
    case 'SetComponentBatch': return accessor(index, new SetComponentBatch())! as SetComponentBatch;
    case 'RemoveComponent': return accessor(index, new RemoveComponent())! as RemoveComponent;
    case 'GetComponents': return accessor(index, new GetComponents())! as GetComponents;
    case 'ScriptCreate': return accessor(index, new ScriptCreate())! as ScriptCreate;
    case 'ScriptUpdate': return accessor(index, new ScriptUpdate())! as ScriptUpdate;
    case 'ScriptDelete': return accessor(index, new ScriptDelete())! as ScriptDelete;
    case 'ScriptListRequest': return accessor(index, new ScriptListRequest())! as ScriptListRequest;
    default: return null;
  }
}
