// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SceneCommand, unionToSceneCommand, unionListToSceneCommand } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-command.js';


export class SceneAction {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneAction {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneAction(bb:flatbuffers.ByteBuffer, obj?:SceneAction):SceneAction {
  return (obj || new SceneAction()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneAction(bb:flatbuffers.ByteBuffer, obj?:SceneAction):SceneAction {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneAction()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

commandType():SceneCommand {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : SceneCommand.NONE;
}

command<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startSceneAction(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCommandType(builder:flatbuffers.Builder, commandType:SceneCommand) {
  builder.addFieldInt8(0, commandType, SceneCommand.NONE);
}

static addCommand(builder:flatbuffers.Builder, commandOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, commandOffset, 0);
}

static endSceneAction(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneAction(builder:flatbuffers.Builder, commandType:SceneCommand, commandOffset:flatbuffers.Offset):flatbuffers.Offset {
  SceneAction.startSceneAction(builder);
  SceneAction.addCommandType(builder, commandType);
  SceneAction.addCommand(builder, commandOffset);
  return SceneAction.endSceneAction(builder);
}
}
