// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Make a scene editable (receives input). At most one scene can be editable
 * at a time — lblib automatically un-editables any currently-editable scene.
 */
export class SceneSetEditable {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneSetEditable {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneSetEditable(bb:flatbuffers.ByteBuffer, obj?:SceneSetEditable):SceneSetEditable {
  return (obj || new SceneSetEditable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneSetEditable(bb:flatbuffers.ByteBuffer, obj?:SceneSetEditable):SceneSetEditable {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneSetEditable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

editable():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startSceneSetEditable(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addEditable(builder:flatbuffers.Builder, editable:boolean) {
  builder.addFieldInt8(1, +editable, +false);
}

static endSceneSetEditable(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneSetEditable(builder:flatbuffers.Builder, sceneId:number, editable:boolean):flatbuffers.Offset {
  SceneSetEditable.startSceneSetEditable(builder);
  SceneSetEditable.addSceneId(builder, sceneId);
  SceneSetEditable.addEditable(builder, editable);
  return SceneSetEditable.endSceneSetEditable(builder);
}
}
