// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Replace the selection set for a scene. Emits SceneSelectionChanged.
 */
export class SceneSetSelection {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneSetSelection {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneSetSelection(bb:flatbuffers.ByteBuffer, obj?:SceneSetSelection):SceneSetSelection {
  return (obj || new SceneSetSelection()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneSetSelection(bb:flatbuffers.ByteBuffer, obj?:SceneSetSelection):SceneSetSelection {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneSetSelection()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

selectedIds(index: number):bigint|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb!.__vector(this.bb_pos + offset) + index * 8) : BigInt(0);
}

selectedIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSceneSetSelection(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addSelectedIds(builder:flatbuffers.Builder, selectedIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, selectedIdsOffset, 0);
}

static createSelectedIdsVector(builder:flatbuffers.Builder, data:bigint[]):flatbuffers.Offset {
  builder.startVector(8, data.length, 8);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]!);
  }
  return builder.endVector();
}

static startSelectedIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 8);
}

static endSceneSetSelection(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneSetSelection(builder:flatbuffers.Builder, sceneId:number, selectedIdsOffset:flatbuffers.Offset):flatbuffers.Offset {
  SceneSetSelection.startSceneSetSelection(builder);
  SceneSetSelection.addSceneId(builder, sceneId);
  SceneSetSelection.addSelectedIds(builder, selectedIdsOffset);
  return SceneSetSelection.endSceneSetSelection(builder);
}
}
