// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Query the full state of one scene (every entity + its components).
 * Returns SceneSnapshot event.
 */
export class SceneSnapshotRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneSnapshotRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneSnapshotRequest(bb:flatbuffers.ByteBuffer, obj?:SceneSnapshotRequest):SceneSnapshotRequest {
  return (obj || new SceneSnapshotRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneSnapshotRequest(bb:flatbuffers.ByteBuffer, obj?:SceneSnapshotRequest):SceneSnapshotRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneSnapshotRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startSceneSnapshotRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static endSceneSnapshotRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneSnapshotRequest(builder:flatbuffers.Builder, sceneId:number):flatbuffers.Offset {
  SceneSnapshotRequest.startSceneSnapshotRequest(builder);
  SceneSnapshotRequest.addSceneId(builder, sceneId);
  return SceneSnapshotRequest.endSceneSnapshotRequest(builder);
}
}
