// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Emitted during reconnect reconciliation if a stored entity_id could not
 * be honored (e.g. collision in the allocator).
 */
export class SceneEntityIdChanged {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneEntityIdChanged {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneEntityIdChanged(bb:flatbuffers.ByteBuffer, obj?:SceneEntityIdChanged):SceneEntityIdChanged {
  return (obj || new SceneEntityIdChanged()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneEntityIdChanged(bb:flatbuffers.ByteBuffer, obj?:SceneEntityIdChanged):SceneEntityIdChanged {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneEntityIdChanged()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

oldEntityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

newEntityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startSceneEntityIdChanged(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addOldEntityId(builder:flatbuffers.Builder, oldEntityId:bigint) {
  builder.addFieldInt64(1, oldEntityId, BigInt('0'));
}

static addNewEntityId(builder:flatbuffers.Builder, newEntityId:bigint) {
  builder.addFieldInt64(2, newEntityId, BigInt('0'));
}

static endSceneEntityIdChanged(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneEntityIdChanged(builder:flatbuffers.Builder, sceneId:number, oldEntityId:bigint, newEntityId:bigint):flatbuffers.Offset {
  SceneEntityIdChanged.startSceneEntityIdChanged(builder);
  SceneEntityIdChanged.addSceneId(builder, sceneId);
  SceneEntityIdChanged.addOldEntityId(builder, oldEntityId);
  SceneEntityIdChanged.addNewEntityId(builder, newEntityId);
  return SceneEntityIdChanged.endSceneEntityIdChanged(builder);
}
}
