// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SceneEvent, unionToSceneEvent, unionListToSceneEvent } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-event.js';


export class SceneEventWrapper {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneEventWrapper {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneEventWrapper(bb:flatbuffers.ByteBuffer, obj?:SceneEventWrapper):SceneEventWrapper {
  return (obj || new SceneEventWrapper()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneEventWrapper(bb:flatbuffers.ByteBuffer, obj?:SceneEventWrapper):SceneEventWrapper {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneEventWrapper()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

eventType():SceneEvent {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : SceneEvent.NONE;
}

event<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startSceneEventWrapper(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addEventType(builder:flatbuffers.Builder, eventType:SceneEvent) {
  builder.addFieldInt8(0, eventType, SceneEvent.NONE);
}

static addEvent(builder:flatbuffers.Builder, eventOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, eventOffset, 0);
}

static endSceneEventWrapper(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneEventWrapper(builder:flatbuffers.Builder, eventType:SceneEvent, eventOffset:flatbuffers.Offset):flatbuffers.Offset {
  SceneEventWrapper.startSceneEventWrapper(builder);
  SceneEventWrapper.addEventType(builder, eventType);
  SceneEventWrapper.addEvent(builder, eventOffset);
  return SceneEventWrapper.endSceneEventWrapper(builder);
}
}
