// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { EntitySnapshot } from '../../../blue-bottle-ipc/league-broadcast/scene/entity-snapshot.js';
import { SceneDescriptor } from '../../../blue-bottle-ipc/league-broadcast/scene/scene-descriptor.js';
import { ScriptAssetSnapshot } from '../../../blue-bottle-ipc/league-broadcast/scene/script-asset-snapshot.js';


/**
 * Full state of a scene, returned by SceneSnapshotRequest.
 */
export class SceneSnapshot {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneSnapshot {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneSnapshot(bb:flatbuffers.ByteBuffer, obj?:SceneSnapshot):SceneSnapshot {
  return (obj || new SceneSnapshot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneSnapshot(bb:flatbuffers.ByteBuffer, obj?:SceneSnapshot):SceneSnapshot {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneSnapshot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

scene(obj?:SceneDescriptor):SceneDescriptor|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SceneDescriptor()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

entities(index: number, obj?:EntitySnapshot):EntitySnapshot|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new EntitySnapshot()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

entitiesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

scripts(index: number, obj?:ScriptAssetSnapshot):ScriptAssetSnapshot|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new ScriptAssetSnapshot()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

scriptsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSceneSnapshot(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addScene(builder:flatbuffers.Builder, sceneOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, sceneOffset, 0);
}

static addEntities(builder:flatbuffers.Builder, entitiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, entitiesOffset, 0);
}

static createEntitiesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startEntitiesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addScripts(builder:flatbuffers.Builder, scriptsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, scriptsOffset, 0);
}

static createScriptsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startScriptsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSceneSnapshot(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // scene
  return offset;
}

static createSceneSnapshot(builder:flatbuffers.Builder, sceneOffset:flatbuffers.Offset, entitiesOffset:flatbuffers.Offset, scriptsOffset:flatbuffers.Offset):flatbuffers.Offset {
  SceneSnapshot.startSceneSnapshot(builder);
  SceneSnapshot.addScene(builder, sceneOffset);
  SceneSnapshot.addEntities(builder, entitiesOffset);
  SceneSnapshot.addScripts(builder, scriptsOffset);
  return SceneSnapshot.endSceneSnapshot(builder);
}
}
