// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Query the list of all loaded scenes (for reconnect reconciliation).
 * Returns SceneList event.
 */
export class SceneListRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneListRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneListRequest(bb:flatbuffers.ByteBuffer, obj?:SceneListRequest):SceneListRequest {
  return (obj || new SceneListRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneListRequest(bb:flatbuffers.ByteBuffer, obj?:SceneListRequest):SceneListRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneListRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startSceneListRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endSceneListRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneListRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  SceneListRequest.startSceneListRequest(builder);
  return SceneListRequest.endSceneListRequest(builder);
}
}
