// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { EntitySnapshot } from '../../../blue-bottle-ipc/league-broadcast/scene/entity-snapshot.js';


/**
 * Container event used both for full-scene snapshots and single-entity
 * GetComponents responses. Callers disambiguate by `entities.length`.
 */
export class SceneEntitiesSnapshot {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneEntitiesSnapshot {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneEntitiesSnapshot(bb:flatbuffers.ByteBuffer, obj?:SceneEntitiesSnapshot):SceneEntitiesSnapshot {
  return (obj || new SceneEntitiesSnapshot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneEntitiesSnapshot(bb:flatbuffers.ByteBuffer, obj?:SceneEntitiesSnapshot):SceneEntitiesSnapshot {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneEntitiesSnapshot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

entities(index: number, obj?:EntitySnapshot):EntitySnapshot|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new EntitySnapshot()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

entitiesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSceneEntitiesSnapshot(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addEntities(builder:flatbuffers.Builder, entitiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, entitiesOffset, 0);
}

static createEntitiesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startEntitiesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSceneEntitiesSnapshot(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneEntitiesSnapshot(builder:flatbuffers.Builder, sceneId:number, entitiesOffset:flatbuffers.Offset):flatbuffers.Offset {
  SceneEntitiesSnapshot.startSceneEntitiesSnapshot(builder);
  SceneEntitiesSnapshot.addSceneId(builder, sceneId);
  SceneEntitiesSnapshot.addEntities(builder, entitiesOffset);
  return SceneEntitiesSnapshot.endSceneEntitiesSnapshot(builder);
}
}
