// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Emitted when a Lua script attached to an entity encounters an error.
 */
export class SceneScriptError {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneScriptError {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneScriptError(bb:flatbuffers.ByteBuffer, obj?:SceneScriptError):SceneScriptError {
  return (obj || new SceneScriptError()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneScriptError(bb:flatbuffers.ByteBuffer, obj?:SceneScriptError):SceneScriptError {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneScriptError()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

entityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

scriptName():string|null
scriptName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
scriptName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

errorMessage():string|null
errorMessage(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
errorMessage(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

lineNumber():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : -1;
}

static startSceneScriptError(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addEntityId(builder:flatbuffers.Builder, entityId:bigint) {
  builder.addFieldInt64(1, entityId, BigInt('0'));
}

static addScriptName(builder:flatbuffers.Builder, scriptNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, scriptNameOffset, 0);
}

static addErrorMessage(builder:flatbuffers.Builder, errorMessageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, errorMessageOffset, 0);
}

static addLineNumber(builder:flatbuffers.Builder, lineNumber:number) {
  builder.addFieldInt32(4, lineNumber, -1);
}

static endSceneScriptError(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSceneScriptError(builder:flatbuffers.Builder, sceneId:number, entityId:bigint, scriptNameOffset:flatbuffers.Offset, errorMessageOffset:flatbuffers.Offset, lineNumber:number):flatbuffers.Offset {
  SceneScriptError.startSceneScriptError(builder);
  SceneScriptError.addSceneId(builder, sceneId);
  SceneScriptError.addEntityId(builder, entityId);
  SceneScriptError.addScriptName(builder, scriptNameOffset);
  SceneScriptError.addErrorMessage(builder, errorMessageOffset);
  SceneScriptError.addLineNumber(builder, lineNumber);
  return SceneScriptError.endSceneScriptError(builder);
}
}
