// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ScriptAssetSnapshot } from '../../../blue-bottle-ipc/league-broadcast/scene/script-asset-snapshot.js';


/**
 * Response to ScriptListRequest.
 */
export class ScriptLibrary {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScriptLibrary {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScriptLibrary(bb:flatbuffers.ByteBuffer, obj?:ScriptLibrary):ScriptLibrary {
  return (obj || new ScriptLibrary()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScriptLibrary(bb:flatbuffers.ByteBuffer, obj?:ScriptLibrary):ScriptLibrary {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScriptLibrary()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

assets(index: number, obj?:ScriptAssetSnapshot):ScriptAssetSnapshot|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ScriptAssetSnapshot()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

assetsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startScriptLibrary(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addAssets(builder:flatbuffers.Builder, assetsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, assetsOffset, 0);
}

static createAssetsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startAssetsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endScriptLibrary(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createScriptLibrary(builder:flatbuffers.Builder, sceneId:number, assetsOffset:flatbuffers.Offset):flatbuffers.Offset {
  ScriptLibrary.startScriptLibrary(builder);
  ScriptLibrary.addSceneId(builder, sceneId);
  ScriptLibrary.addAssets(builder, assetsOffset);
  return ScriptLibrary.endScriptLibrary(builder);
}
}
