// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ScriptAssetSnapshot } from '../../../blue-bottle-ipc/league-broadcast/scene/script-asset-snapshot.js';


/**
 * Emitted when a script asset is created or updated.
 */
export class ScriptAssetChanged {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScriptAssetChanged {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScriptAssetChanged(bb:flatbuffers.ByteBuffer, obj?:ScriptAssetChanged):ScriptAssetChanged {
  return (obj || new ScriptAssetChanged()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScriptAssetChanged(bb:flatbuffers.ByteBuffer, obj?:ScriptAssetChanged):ScriptAssetChanged {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScriptAssetChanged()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

asset(obj?:ScriptAssetSnapshot):ScriptAssetSnapshot|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ScriptAssetSnapshot()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startScriptAssetChanged(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addAsset(builder:flatbuffers.Builder, assetOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, assetOffset, 0);
}

static endScriptAssetChanged(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // asset
  return offset;
}

}
