// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Delete a script asset and remove all entity references to it.
 */
export class ScriptDelete {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScriptDelete {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScriptDelete(bb:flatbuffers.ByteBuffer, obj?:ScriptDelete):ScriptDelete {
  return (obj || new ScriptDelete()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScriptDelete(bb:flatbuffers.ByteBuffer, obj?:ScriptDelete):ScriptDelete {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScriptDelete()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

scriptId():string|null
scriptId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
scriptId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startScriptDelete(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addScriptId(builder:flatbuffers.Builder, scriptIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, scriptIdOffset, 0);
}

static endScriptDelete(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // script_id
  return offset;
}

static createScriptDelete(builder:flatbuffers.Builder, sceneId:number, scriptIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  ScriptDelete.startScriptDelete(builder);
  ScriptDelete.addSceneId(builder, sceneId);
  ScriptDelete.addScriptId(builder, scriptIdOffset);
  return ScriptDelete.endScriptDelete(builder);
}
}
