// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Update an existing script asset (name and/or content).
 */
export class ScriptUpdate {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScriptUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScriptUpdate(bb:flatbuffers.ByteBuffer, obj?:ScriptUpdate):ScriptUpdate {
  return (obj || new ScriptUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScriptUpdate(bb:flatbuffers.ByteBuffer, obj?:ScriptUpdate):ScriptUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScriptUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

scriptId():string|null
scriptId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
scriptId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

content():string|null
content(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
content(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startScriptUpdate(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addScriptId(builder:flatbuffers.Builder, scriptIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, scriptIdOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nameOffset, 0);
}

static addContent(builder:flatbuffers.Builder, contentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, contentOffset, 0);
}

static endScriptUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // script_id
  return offset;
}

static createScriptUpdate(builder:flatbuffers.Builder, sceneId:number, scriptIdOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, contentOffset:flatbuffers.Offset):flatbuffers.Offset {
  ScriptUpdate.startScriptUpdate(builder);
  ScriptUpdate.addSceneId(builder, sceneId);
  ScriptUpdate.addScriptId(builder, scriptIdOffset);
  ScriptUpdate.addName(builder, nameOffset);
  ScriptUpdate.addContent(builder, contentOffset);
  return ScriptUpdate.endScriptUpdate(builder);
}
}
