// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ScriptVariableSnapshot } from '../../../blue-bottle-ipc/league-broadcast/scene/script-variable-snapshot.js';


/**
 * Snapshot of a single script asset for API responses.
 */
export class ScriptAssetSnapshot {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScriptAssetSnapshot {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScriptAssetSnapshot(bb:flatbuffers.ByteBuffer, obj?:ScriptAssetSnapshot):ScriptAssetSnapshot {
  return (obj || new ScriptAssetSnapshot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScriptAssetSnapshot(bb:flatbuffers.ByteBuffer, obj?:ScriptAssetSnapshot):ScriptAssetSnapshot {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScriptAssetSnapshot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

content():string|null
content(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
content(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

variables(index: number, obj?:ScriptVariableSnapshot):ScriptVariableSnapshot|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new ScriptVariableSnapshot()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

variablesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startScriptAssetSnapshot(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addContent(builder:flatbuffers.Builder, contentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, contentOffset, 0);
}

static addVariables(builder:flatbuffers.Builder, variablesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, variablesOffset, 0);
}

static createVariablesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startVariablesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endScriptAssetSnapshot(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // id
  return offset;
}

static createScriptAssetSnapshot(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, contentOffset:flatbuffers.Offset, variablesOffset:flatbuffers.Offset):flatbuffers.Offset {
  ScriptAssetSnapshot.startScriptAssetSnapshot(builder);
  ScriptAssetSnapshot.addId(builder, idOffset);
  ScriptAssetSnapshot.addName(builder, nameOffset);
  ScriptAssetSnapshot.addContent(builder, contentOffset);
  ScriptAssetSnapshot.addVariables(builder, variablesOffset);
  return ScriptAssetSnapshot.endScriptAssetSnapshot(builder);
}
}
