// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Request the full script library for a scene.
 */
export class ScriptListRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScriptListRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScriptListRequest(bb:flatbuffers.ByteBuffer, obj?:ScriptListRequest):ScriptListRequest {
  return (obj || new ScriptListRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScriptListRequest(bb:flatbuffers.ByteBuffer, obj?:ScriptListRequest):ScriptListRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScriptListRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startScriptListRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static endScriptListRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createScriptListRequest(builder:flatbuffers.Builder, sceneId:number):flatbuffers.Offset {
  ScriptListRequest.startScriptListRequest(builder);
  ScriptListRequest.addSceneId(builder, sceneId);
  return ScriptListRequest.endScriptListRequest(builder);
}
}
