// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Log level for script log messages.
 */
export enum ScriptLogLevel {
  Debug = 0,
  Info = 1,
  Warning = 2,
  Error = 3
}
