// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Create a new script asset in the scene's library.
 */
export class ScriptCreate {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScriptCreate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScriptCreate(bb:flatbuffers.ByteBuffer, obj?:ScriptCreate):ScriptCreate {
  return (obj || new ScriptCreate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScriptCreate(bb:flatbuffers.ByteBuffer, obj?:ScriptCreate):ScriptCreate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScriptCreate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sceneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

content():string|null
content(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
content(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startScriptCreate(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addSceneId(builder:flatbuffers.Builder, sceneId:number) {
  builder.addFieldInt32(0, sceneId, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addContent(builder:flatbuffers.Builder, contentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, contentOffset, 0);
}

static endScriptCreate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createScriptCreate(builder:flatbuffers.Builder, sceneId:number, nameOffset:flatbuffers.Offset, contentOffset:flatbuffers.Offset):flatbuffers.Offset {
  ScriptCreate.startScriptCreate(builder);
  ScriptCreate.addSceneId(builder, sceneId);
  ScriptCreate.addName(builder, nameOffset);
  ScriptCreate.addContent(builder, contentOffset);
  return ScriptCreate.endScriptCreate(builder);
}
}
