// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SetComponent } from '../../../blue-bottle-ipc/league-broadcast/scene/set-component.js';


/**
 * Batched SetComponent. Items may target different entities.
 */
export class SetComponentBatch {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SetComponentBatch {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSetComponentBatch(bb:flatbuffers.ByteBuffer, obj?:SetComponentBatch):SetComponentBatch {
  return (obj || new SetComponentBatch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSetComponentBatch(bb:flatbuffers.ByteBuffer, obj?:SetComponentBatch):SetComponentBatch {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SetComponentBatch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

items(index: number, obj?:SetComponent):SetComponent|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SetComponent()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

itemsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSetComponentBatch(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addItems(builder:flatbuffers.Builder, itemsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, itemsOffset, 0);
}

static createItemsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startItemsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSetComponentBatch(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSetComponentBatch(builder:flatbuffers.Builder, itemsOffset:flatbuffers.Offset):flatbuffers.Offset {
  SetComponentBatch.startSetComponentBatch(builder);
  SetComponentBatch.addItems(builder, itemsOffset);
  return SetComponentBatch.endSetComponentBatch(builder);
}
}
