// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Component, unionToComponent, unionListToComponent } from '../../../blue-bottle-ipc/league-broadcast/entity/Component.js';


/**
 * Replace one component on one entity (full-component semantics — receiver
 * always overwrites). To re-parent: SetComponent(Transform) with the new
 * parent_id and unchanged pos/rot/scale.
 */
export class SetComponent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SetComponent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSetComponent(bb:flatbuffers.ByteBuffer, obj?:SetComponent):SetComponent {
  return (obj || new SetComponent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSetComponent(bb:flatbuffers.ByteBuffer, obj?:SetComponent):SetComponent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SetComponent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

entityId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

componentType():Component {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Component.NONE;
}

component<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startSetComponent(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addEntityId(builder:flatbuffers.Builder, entityId:bigint) {
  builder.addFieldInt64(0, entityId, BigInt('0'));
}

static addComponentType(builder:flatbuffers.Builder, componentType:Component) {
  builder.addFieldInt8(1, componentType, Component.NONE);
}

static addComponent(builder:flatbuffers.Builder, componentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, componentOffset, 0);
}

static endSetComponent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSetComponent(builder:flatbuffers.Builder, entityId:bigint, componentType:Component, componentOffset:flatbuffers.Offset):flatbuffers.Offset {
  SetComponent.startSetComponent(builder);
  SetComponent.addEntityId(builder, entityId);
  SetComponent.addComponentType(builder, componentType);
  SetComponent.addComponent(builder, componentOffset);
  return SetComponent.endSetComponent(builder);
}
}
