// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AssetCreate } from '../../../blue-bottle-ipc/league-broadcast/commands/asset-create.js';


export class AssetCreateBatch {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AssetCreateBatch {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAssetCreateBatch(bb:flatbuffers.ByteBuffer, obj?:AssetCreateBatch):AssetCreateBatch {
  return (obj || new AssetCreateBatch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAssetCreateBatch(bb:flatbuffers.ByteBuffer, obj?:AssetCreateBatch):AssetCreateBatch {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AssetCreateBatch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

reqs(index: number, obj?:AssetCreate):AssetCreate|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new AssetCreate()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

reqsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startAssetCreateBatch(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addReqs(builder:flatbuffers.Builder, reqsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, reqsOffset, 0);
}

static createReqsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startReqsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endAssetCreateBatch(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAssetCreateBatch(builder:flatbuffers.Builder, reqsOffset:flatbuffers.Offset):flatbuffers.Offset {
  AssetCreateBatch.startAssetCreateBatch(builder);
  AssetCreateBatch.addReqs(builder, reqsOffset);
  return AssetCreateBatch.endAssetCreateBatch(builder);
}
}
