// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AssetType } from '../../../blue-bottle-ipc/league-broadcast/commands/asset-type.js';


export class AssetCreate {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AssetCreate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAssetCreate(bb:flatbuffers.ByteBuffer, obj?:AssetCreate):AssetCreate {
  return (obj || new AssetCreate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAssetCreate(bb:flatbuffers.ByteBuffer, obj?:AssetCreate):AssetCreate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AssetCreate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():AssetType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AssetType.texture;
}

path():string|null
path(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
path(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

id():bigint|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startAssetCreate(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addType(builder:flatbuffers.Builder, type:AssetType) {
  builder.addFieldInt8(0, type, AssetType.texture);
}

static addPath(builder:flatbuffers.Builder, pathOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, pathOffset, 0);
}

static addId(builder:flatbuffers.Builder, id:bigint) {
  builder.addFieldInt64(2, id, null);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, nameOffset, 0);
}

static endAssetCreate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAssetCreate(builder:flatbuffers.Builder, type:AssetType, pathOffset:flatbuffers.Offset, id:bigint|null, nameOffset:flatbuffers.Offset):flatbuffers.Offset {
  AssetCreate.startAssetCreate(builder);
  AssetCreate.addType(builder, type);
  AssetCreate.addPath(builder, pathOffset);
  if (id !== null)
    AssetCreate.addId(builder, id);
  AssetCreate.addName(builder, nameOffset);
  return AssetCreate.endAssetCreate(builder);
}
}
