// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { IdWrapper } from '../../../blue-bottle-ipc/league-broadcast/commands/id-wrapper.js';


export enum AssetIdentifier {
  NONE = 0,
  id = 1,
  name = 2
}

export function unionToAssetIdentifier(
  type: AssetIdentifier,
  accessor: (obj:IdWrapper|string) => IdWrapper|string|null
): IdWrapper|string|null {
  switch(AssetIdentifier[type]) {
    case 'NONE': return null; 
    case 'id': return accessor(new IdWrapper())! as IdWrapper;
    case 'name': return accessor('') as string;
    default: return null;
  }
}

export function unionListToAssetIdentifier(
  type: AssetIdentifier, 
  accessor: (index: number, obj:IdWrapper|string) => IdWrapper|string|null, 
  index: number
): IdWrapper|string|null {
  switch(AssetIdentifier[type]) {
    case 'NONE': return null; 
    case 'id': return accessor(index, new IdWrapper())! as IdWrapper;
    case 'name': return accessor(index, '') as string;
    default: return null;
  }
}
