// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum AssetType {
  texture = 0,
  model = 1,
  streamTexture = 2,
  font = 3
}
