// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * ICE server configuration for WebRTC stream texture negotiation.
 */
export class IceServer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):IceServer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsIceServer(bb:flatbuffers.ByteBuffer, obj?:IceServer):IceServer {
  return (obj || new IceServer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsIceServer(bb:flatbuffers.ByteBuffer, obj?:IceServer):IceServer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new IceServer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

urls(index: number):string
urls(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
urls(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

urlsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

username():string|null
username(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
username(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

credential():string|null
credential(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
credential(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startIceServer(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addUrls(builder:flatbuffers.Builder, urlsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, urlsOffset, 0);
}

static createUrlsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startUrlsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addUsername(builder:flatbuffers.Builder, usernameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, usernameOffset, 0);
}

static addCredential(builder:flatbuffers.Builder, credentialOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, credentialOffset, 0);
}

static endIceServer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createIceServer(builder:flatbuffers.Builder, urlsOffset:flatbuffers.Offset, usernameOffset:flatbuffers.Offset, credentialOffset:flatbuffers.Offset):flatbuffers.Offset {
  IceServer.startIceServer(builder);
  IceServer.addUrls(builder, urlsOffset);
  IceServer.addUsername(builder, usernameOffset);
  IceServer.addCredential(builder, credentialOffset);
  return IceServer.endIceServer(builder);
}
}
