// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class IdWrapper {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):IdWrapper {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsIdWrapper(bb:flatbuffers.ByteBuffer, obj?:IdWrapper):IdWrapper {
  return (obj || new IdWrapper()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsIdWrapper(bb:flatbuffers.ByteBuffer, obj?:IdWrapper):IdWrapper {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new IdWrapper()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startIdWrapper(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, id:bigint) {
  builder.addFieldInt64(0, id, BigInt('0'));
}

static endIdWrapper(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createIdWrapper(builder:flatbuffers.Builder, id:bigint):flatbuffers.Offset {
  IdWrapper.startIdWrapper(builder);
  IdWrapper.addId(builder, id);
  return IdWrapper.endIdWrapper(builder);
}
}
