// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AssetIdentifier, unionToAssetIdentifier, unionListToAssetIdentifier } from '../../../blue-bottle-ipc/league-broadcast/commands/asset-identifier.js';


export class StreamTextureStatusRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StreamTextureStatusRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStreamTextureStatusRequest(bb:flatbuffers.ByteBuffer, obj?:StreamTextureStatusRequest):StreamTextureStatusRequest {
  return (obj || new StreamTextureStatusRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStreamTextureStatusRequest(bb:flatbuffers.ByteBuffer, obj?:StreamTextureStatusRequest):StreamTextureStatusRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StreamTextureStatusRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

identType():AssetIdentifier {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AssetIdentifier.NONE;
}

ident<T extends flatbuffers.Table>(obj:any|string):any|string|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union_with_string(obj, this.bb_pos + offset) : null;
}

static startStreamTextureStatusRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addIdentType(builder:flatbuffers.Builder, identType:AssetIdentifier) {
  builder.addFieldInt8(0, identType, AssetIdentifier.NONE);
}

static addIdent(builder:flatbuffers.Builder, identOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, identOffset, 0);
}

static endStreamTextureStatusRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStreamTextureStatusRequest(builder:flatbuffers.Builder, identType:AssetIdentifier, identOffset:flatbuffers.Offset):flatbuffers.Offset {
  StreamTextureStatusRequest.startStreamTextureStatusRequest(builder);
  StreamTextureStatusRequest.addIdentType(builder, identType);
  StreamTextureStatusRequest.addIdent(builder, identOffset);
  return StreamTextureStatusRequest.endStreamTextureStatusRequest(builder);
}
}
