// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AssetIdentifier, unionToAssetIdentifier, unionListToAssetIdentifier } from '../../../blue-bottle-ipc/league-broadcast/commands/asset-identifier.js';


/**
 * Request: apply the SDP answer returned by a WHEP endpoint.
 */
export class StreamTextureApplySDPAnswer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StreamTextureApplySDPAnswer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStreamTextureApplySDPAnswer(bb:flatbuffers.ByteBuffer, obj?:StreamTextureApplySDPAnswer):StreamTextureApplySDPAnswer {
  return (obj || new StreamTextureApplySDPAnswer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStreamTextureApplySDPAnswer(bb:flatbuffers.ByteBuffer, obj?:StreamTextureApplySDPAnswer):StreamTextureApplySDPAnswer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StreamTextureApplySDPAnswer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

identType():AssetIdentifier {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AssetIdentifier.NONE;
}

ident<T extends flatbuffers.Table>(obj:any|string):any|string|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union_with_string(obj, this.bb_pos + offset) : null;
}

sdpAnswer():string|null
sdpAnswer(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sdpAnswer(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startStreamTextureApplySDPAnswer(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addIdentType(builder:flatbuffers.Builder, identType:AssetIdentifier) {
  builder.addFieldInt8(0, identType, AssetIdentifier.NONE);
}

static addIdent(builder:flatbuffers.Builder, identOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, identOffset, 0);
}

static addSdpAnswer(builder:flatbuffers.Builder, sdpAnswerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, sdpAnswerOffset, 0);
}

static endStreamTextureApplySDPAnswer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 8) // sdp_answer
  return offset;
}

static createStreamTextureApplySDPAnswer(builder:flatbuffers.Builder, identType:AssetIdentifier, identOffset:flatbuffers.Offset, sdpAnswerOffset:flatbuffers.Offset):flatbuffers.Offset {
  StreamTextureApplySDPAnswer.startStreamTextureApplySDPAnswer(builder);
  StreamTextureApplySDPAnswer.addIdentType(builder, identType);
  StreamTextureApplySDPAnswer.addIdent(builder, identOffset);
  StreamTextureApplySDPAnswer.addSdpAnswer(builder, sdpAnswerOffset);
  return StreamTextureApplySDPAnswer.endStreamTextureApplySDPAnswer(builder);
}
}
