// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum StreamTextureState {
  Idle = 0,
  Connecting = 1,
  Connected = 2,
  Disconnected = 3,
  Failed = 4
}
