// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { StreamTextureState } from '../../../blue-bottle-ipc/league-broadcast/commands/stream-texture-state.js';


export class StreamTextureStatus {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StreamTextureStatus {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStreamTextureStatus(bb:flatbuffers.ByteBuffer, obj?:StreamTextureStatus):StreamTextureStatus {
  return (obj || new StreamTextureStatus()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStreamTextureStatus(bb:flatbuffers.ByteBuffer, obj?:StreamTextureStatus):StreamTextureStatus {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StreamTextureStatus()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

state():StreamTextureState {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : StreamTextureState.Idle;
}

codec():string|null
codec(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
codec(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

width():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

height():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

lastFrameUnixMs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

error():string|null
error(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
error(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startStreamTextureStatus(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addState(builder:flatbuffers.Builder, state:StreamTextureState) {
  builder.addFieldInt8(0, state, StreamTextureState.Idle);
}

static addCodec(builder:flatbuffers.Builder, codecOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, codecOffset, 0);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldInt32(2, width, 0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldInt32(3, height, 0);
}

static addLastFrameUnixMs(builder:flatbuffers.Builder, lastFrameUnixMs:bigint) {
  builder.addFieldInt64(4, lastFrameUnixMs, BigInt('0'));
}

static addError(builder:flatbuffers.Builder, errorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, errorOffset, 0);
}

static endStreamTextureStatus(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStreamTextureStatus(builder:flatbuffers.Builder, state:StreamTextureState, codecOffset:flatbuffers.Offset, width:number, height:number, lastFrameUnixMs:bigint, errorOffset:flatbuffers.Offset):flatbuffers.Offset {
  StreamTextureStatus.startStreamTextureStatus(builder);
  StreamTextureStatus.addState(builder, state);
  StreamTextureStatus.addCodec(builder, codecOffset);
  StreamTextureStatus.addWidth(builder, width);
  StreamTextureStatus.addHeight(builder, height);
  StreamTextureStatus.addLastFrameUnixMs(builder, lastFrameUnixMs);
  StreamTextureStatus.addError(builder, errorOffset);
  return StreamTextureStatus.endStreamTextureStatus(builder);
}
}
