// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AssetIdentifier, unionToAssetIdentifier, unionListToAssetIdentifier } from '../../../blue-bottle-ipc/league-broadcast/commands/asset-identifier.js';


/**
 * Request: close an active WHIP session on a stream texture asset.
 */
export class StreamTextureCloseSession {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StreamTextureCloseSession {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStreamTextureCloseSession(bb:flatbuffers.ByteBuffer, obj?:StreamTextureCloseSession):StreamTextureCloseSession {
  return (obj || new StreamTextureCloseSession()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStreamTextureCloseSession(bb:flatbuffers.ByteBuffer, obj?:StreamTextureCloseSession):StreamTextureCloseSession {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StreamTextureCloseSession()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

identType():AssetIdentifier {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AssetIdentifier.NONE;
}

ident<T extends flatbuffers.Table>(obj:any|string):any|string|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union_with_string(obj, this.bb_pos + offset) : null;
}

static startStreamTextureCloseSession(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addIdentType(builder:flatbuffers.Builder, identType:AssetIdentifier) {
  builder.addFieldInt8(0, identType, AssetIdentifier.NONE);
}

static addIdent(builder:flatbuffers.Builder, identOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, identOffset, 0);
}

static endStreamTextureCloseSession(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStreamTextureCloseSession(builder:flatbuffers.Builder, identType:AssetIdentifier, identOffset:flatbuffers.Offset):flatbuffers.Offset {
  StreamTextureCloseSession.startStreamTextureCloseSession(builder);
  StreamTextureCloseSession.addIdentType(builder, identType);
  StreamTextureCloseSession.addIdent(builder, identOffset);
  return StreamTextureCloseSession.endStreamTextureCloseSession(builder);
}
}
