// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AssetIdentifier, unionToAssetIdentifier, unionListToAssetIdentifier } from '../../../blue-bottle-ipc/league-broadcast/commands/asset-identifier.js';
import { IceServer } from '../../../blue-bottle-ipc/league-broadcast/commands/ice-server.js';


/**
 * Request: create an H.264 recv-only SDP offer for WHEP playback.
 */
export class StreamTextureCreateSDPOffer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StreamTextureCreateSDPOffer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStreamTextureCreateSDPOffer(bb:flatbuffers.ByteBuffer, obj?:StreamTextureCreateSDPOffer):StreamTextureCreateSDPOffer {
  return (obj || new StreamTextureCreateSDPOffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStreamTextureCreateSDPOffer(bb:flatbuffers.ByteBuffer, obj?:StreamTextureCreateSDPOffer):StreamTextureCreateSDPOffer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StreamTextureCreateSDPOffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

identType():AssetIdentifier {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AssetIdentifier.NONE;
}

ident<T extends flatbuffers.Table>(obj:any|string):any|string|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union_with_string(obj, this.bb_pos + offset) : null;
}

iceServers(index: number, obj?:IceServer):IceServer|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new IceServer()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

iceServersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startStreamTextureCreateSDPOffer(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addIdentType(builder:flatbuffers.Builder, identType:AssetIdentifier) {
  builder.addFieldInt8(0, identType, AssetIdentifier.NONE);
}

static addIdent(builder:flatbuffers.Builder, identOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, identOffset, 0);
}

static addIceServers(builder:flatbuffers.Builder, iceServersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, iceServersOffset, 0);
}

static createIceServersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startIceServersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endStreamTextureCreateSDPOffer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStreamTextureCreateSDPOffer(builder:flatbuffers.Builder, identType:AssetIdentifier, identOffset:flatbuffers.Offset, iceServersOffset:flatbuffers.Offset):flatbuffers.Offset {
  StreamTextureCreateSDPOffer.startStreamTextureCreateSDPOffer(builder);
  StreamTextureCreateSDPOffer.addIdentType(builder, identType);
  StreamTextureCreateSDPOffer.addIdent(builder, identOffset);
  StreamTextureCreateSDPOffer.addIceServers(builder, iceServersOffset);
  return StreamTextureCreateSDPOffer.endStreamTextureCreateSDPOffer(builder);
}
}
