// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AssetIdentifier, unionToAssetIdentifier, unionListToAssetIdentifier } from '../../../blue-bottle-ipc/league-broadcast/commands/asset-identifier.js';
import { IceServer } from '../../../blue-bottle-ipc/league-broadcast/commands/ice-server.js';


/**
 * Request: send an SDP offer to a stream texture asset to initiate WHIP.
 * The asset must be of type streamTexture. Response is StreamTextureSDPAnswer.
 */
export class StreamTextureSDPOffer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StreamTextureSDPOffer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStreamTextureSDPOffer(bb:flatbuffers.ByteBuffer, obj?:StreamTextureSDPOffer):StreamTextureSDPOffer {
  return (obj || new StreamTextureSDPOffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStreamTextureSDPOffer(bb:flatbuffers.ByteBuffer, obj?:StreamTextureSDPOffer):StreamTextureSDPOffer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StreamTextureSDPOffer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

identType():AssetIdentifier {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AssetIdentifier.NONE;
}

ident<T extends flatbuffers.Table>(obj:any|string):any|string|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union_with_string(obj, this.bb_pos + offset) : null;
}

sdpOffer():string|null
sdpOffer(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sdpOffer(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

iceServers(index: number, obj?:IceServer):IceServer|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new IceServer()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

iceServersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startStreamTextureSDPOffer(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addIdentType(builder:flatbuffers.Builder, identType:AssetIdentifier) {
  builder.addFieldInt8(0, identType, AssetIdentifier.NONE);
}

static addIdent(builder:flatbuffers.Builder, identOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, identOffset, 0);
}

static addSdpOffer(builder:flatbuffers.Builder, sdpOfferOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, sdpOfferOffset, 0);
}

static addIceServers(builder:flatbuffers.Builder, iceServersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, iceServersOffset, 0);
}

static createIceServersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startIceServersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endStreamTextureSDPOffer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 8) // sdp_offer
  return offset;
}

static createStreamTextureSDPOffer(builder:flatbuffers.Builder, identType:AssetIdentifier, identOffset:flatbuffers.Offset, sdpOfferOffset:flatbuffers.Offset, iceServersOffset:flatbuffers.Offset):flatbuffers.Offset {
  StreamTextureSDPOffer.startStreamTextureSDPOffer(builder);
  StreamTextureSDPOffer.addIdentType(builder, identType);
  StreamTextureSDPOffer.addIdent(builder, identOffset);
  StreamTextureSDPOffer.addSdpOffer(builder, sdpOfferOffset);
  StreamTextureSDPOffer.addIceServers(builder, iceServersOffset);
  return StreamTextureSDPOffer.endStreamTextureSDPOffer(builder);
}
}
