// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class StreamTextureSDPResult {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StreamTextureSDPResult {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStreamTextureSDPResult(bb:flatbuffers.ByteBuffer, obj?:StreamTextureSDPResult):StreamTextureSDPResult {
  return (obj || new StreamTextureSDPResult()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStreamTextureSDPResult(bb:flatbuffers.ByteBuffer, obj?:StreamTextureSDPResult):StreamTextureSDPResult {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StreamTextureSDPResult()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sdp():string|null
sdp(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sdp(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

error():string|null
error(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
error(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startStreamTextureSDPResult(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSdp(builder:flatbuffers.Builder, sdpOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, sdpOffset, 0);
}

static addError(builder:flatbuffers.Builder, errorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, errorOffset, 0);
}

static endStreamTextureSDPResult(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStreamTextureSDPResult(builder:flatbuffers.Builder, sdpOffset:flatbuffers.Offset, errorOffset:flatbuffers.Offset):flatbuffers.Offset {
  StreamTextureSDPResult.startStreamTextureSDPResult(builder);
  StreamTextureSDPResult.addSdp(builder, sdpOffset);
  StreamTextureSDPResult.addError(builder, errorOffset);
  return StreamTextureSDPResult.endStreamTextureSDPResult(builder);
}
}
